!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
DLG_CURSES_WACS_ARRAY	/usr/include/dlg_config.h	6;"	d
DLG_CURSES_WACS_SYMBOLS	/usr/include/dlg_config.h	7;"	d
DLG_DIALOG_PATCHDATE	/usr/include/dlg_config.h	8;"	d
DLG_DIALOG_VERSION	/usr/include/dlg_config.h	9;"	d
DLG_ENABLE_NLS	/usr/include/dlg_config.h	10;"	d
DLG_HAVE_ALLOCA	/usr/include/dlg_config.h	11;"	d
DLG_HAVE_ALLOCA_H	/usr/include/dlg_config.h	12;"	d
DLG_HAVE_ARGZ_H	/usr/include/dlg_config.h	13;"	d
DLG_HAVE_BTOWC	/usr/include/dlg_config.h	14;"	d
DLG_HAVE_COLOR	/usr/include/dlg_config.h	15;"	d
DLG_HAVE_DCGETTEXT	/usr/include/dlg_config.h	16;"	d
DLG_HAVE_DIRENT_H	/usr/include/dlg_config.h	17;"	d
DLG_HAVE_DLG_FORMBOX	/usr/include/dlg_config.h	18;"	d
DLG_HAVE_DLG_GAUGE	/usr/include/dlg_config.h	19;"	d
DLG_HAVE_DLG_MIXEDFORM	/usr/include/dlg_config.h	20;"	d
DLG_HAVE_DLG_TAILBOX	/usr/include/dlg_config.h	21;"	d
DLG_HAVE_DLG_TRACE	/usr/include/dlg_config.h	22;"	d
DLG_HAVE_FEOF_UNLOCKED	/usr/include/dlg_config.h	23;"	d
DLG_HAVE_FGETS_UNLOCKED	/usr/include/dlg_config.h	24;"	d
DLG_HAVE_FLUSHINP	/usr/include/dlg_config.h	25;"	d
DLG_HAVE_FSEEKO	/usr/include/dlg_config.h	26;"	d
DLG_HAVE_GETATTRS	/usr/include/dlg_config.h	27;"	d
DLG_HAVE_GETBEGX	/usr/include/dlg_config.h	28;"	d
DLG_HAVE_GETBEGY	/usr/include/dlg_config.h	29;"	d
DLG_HAVE_GETBEGYX	/usr/include/dlg_config.h	30;"	d
DLG_HAVE_GETCURX	/usr/include/dlg_config.h	31;"	d
DLG_HAVE_GETCURY	/usr/include/dlg_config.h	32;"	d
DLG_HAVE_GETCWD	/usr/include/dlg_config.h	33;"	d
DLG_HAVE_GETEGID	/usr/include/dlg_config.h	34;"	d
DLG_HAVE_GETEUID	/usr/include/dlg_config.h	35;"	d
DLG_HAVE_GETGID	/usr/include/dlg_config.h	36;"	d
DLG_HAVE_GETMAXX	/usr/include/dlg_config.h	37;"	d
DLG_HAVE_GETMAXY	/usr/include/dlg_config.h	38;"	d
DLG_HAVE_GETMAXYX	/usr/include/dlg_config.h	39;"	d
DLG_HAVE_GETPAGESIZE	/usr/include/dlg_config.h	40;"	d
DLG_HAVE_GETPARX	/usr/include/dlg_config.h	41;"	d
DLG_HAVE_GETPARY	/usr/include/dlg_config.h	42;"	d
DLG_HAVE_GETPARYX	/usr/include/dlg_config.h	43;"	d
DLG_HAVE_GETTEXT	/usr/include/dlg_config.h	44;"	d
DLG_HAVE_GETUID	/usr/include/dlg_config.h	45;"	d
DLG_HAVE_ICONV	/usr/include/dlg_config.h	46;"	d
DLG_HAVE_INTTYPES_H	/usr/include/dlg_config.h	47;"	d
DLG_HAVE_LANGINFO_CODESET	/usr/include/dlg_config.h	48;"	d
DLG_HAVE_LC_MESSAGES	/usr/include/dlg_config.h	49;"	d
DLG_HAVE_LIBINTL_H	/usr/include/dlg_config.h	50;"	d
DLG_HAVE_LIBNCURSESW	/usr/include/dlg_config.h	51;"	d
DLG_HAVE_LIMITS_H	/usr/include/dlg_config.h	52;"	d
DLG_HAVE_LOCALE_H	/usr/include/dlg_config.h	53;"	d
DLG_HAVE_MALLOC_H	/usr/include/dlg_config.h	54;"	d
DLG_HAVE_MBLEN	/usr/include/dlg_config.h	55;"	d
DLG_HAVE_MBRLEN	/usr/include/dlg_config.h	56;"	d
DLG_HAVE_MBRTOWC	/usr/include/dlg_config.h	57;"	d
DLG_HAVE_MBSTATE_T	/usr/include/dlg_config.h	58;"	d
DLG_HAVE_MBTOWC	/usr/include/dlg_config.h	59;"	d
DLG_HAVE_MEMORY_H	/usr/include/dlg_config.h	60;"	d
DLG_HAVE_MEMPCPY	/usr/include/dlg_config.h	61;"	d
DLG_HAVE_MIXEDGAUGE	/usr/include/dlg_config.h	62;"	d
DLG_HAVE_MMAP	/usr/include/dlg_config.h	63;"	d
DLG_HAVE_MUNMAP	/usr/include/dlg_config.h	64;"	d
DLG_HAVE_NCURSESW_NCURSES_H	/usr/include/dlg_config.h	65;"	d
DLG_HAVE_NCURSESW_TERM_H	/usr/include/dlg_config.h	66;"	d
DLG_HAVE_NCURSESW_UNCTRL_H	/usr/include/dlg_config.h	67;"	d
DLG_HAVE_NL_TYPES_H	/usr/include/dlg_config.h	68;"	d
DLG_HAVE_PUTENV	/usr/include/dlg_config.h	69;"	d
DLG_HAVE_RC_FILE	/usr/include/dlg_config.h	70;"	d
DLG_HAVE_SEARCH_H	/usr/include/dlg_config.h	71;"	d
DLG_HAVE_SETENV	/usr/include/dlg_config.h	72;"	d
DLG_HAVE_SETLOCALE	/usr/include/dlg_config.h	73;"	d
DLG_HAVE_STDDEF_H	/usr/include/dlg_config.h	74;"	d
DLG_HAVE_STDINT_H	/usr/include/dlg_config.h	75;"	d
DLG_HAVE_STDLIB_H	/usr/include/dlg_config.h	76;"	d
DLG_HAVE_STPCPY	/usr/include/dlg_config.h	77;"	d
DLG_HAVE_STRCASECMP	/usr/include/dlg_config.h	78;"	d
DLG_HAVE_STRCHR	/usr/include/dlg_config.h	79;"	d
DLG_HAVE_STRDUP	/usr/include/dlg_config.h	80;"	d
DLG_HAVE_STRFTIME	/usr/include/dlg_config.h	81;"	d
DLG_HAVE_STRINGS_H	/usr/include/dlg_config.h	82;"	d
DLG_HAVE_STRING_H	/usr/include/dlg_config.h	83;"	d
DLG_HAVE_STRTOUL	/usr/include/dlg_config.h	84;"	d
DLG_HAVE_SYS_PARAM_H	/usr/include/dlg_config.h	85;"	d
DLG_HAVE_SYS_STAT_H	/usr/include/dlg_config.h	86;"	d
DLG_HAVE_SYS_TYPES_H	/usr/include/dlg_config.h	87;"	d
DLG_HAVE_SYS_WAIT_H	/usr/include/dlg_config.h	88;"	d
DLG_HAVE_TSEARCH	/usr/include/dlg_config.h	89;"	d
DLG_HAVE_TYPE_CHTYPE	/usr/include/dlg_config.h	90;"	d
DLG_HAVE_UNCTRL_H	/usr/include/dlg_config.h	91;"	d
DLG_HAVE_UNISTD_H	/usr/include/dlg_config.h	92;"	d
DLG_HAVE_USE_DEFAULT_COLORS	/usr/include/dlg_config.h	93;"	d
DLG_HAVE_WAITPID	/usr/include/dlg_config.h	94;"	d
DLG_HAVE_WCHGAT	/usr/include/dlg_config.h	95;"	d
DLG_HAVE_WCSRTOMBS	/usr/include/dlg_config.h	96;"	d
DLG_HAVE_WCSTOMBS	/usr/include/dlg_config.h	97;"	d
DLG_HAVE_WCTOB	/usr/include/dlg_config.h	98;"	d
DLG_HAVE_WCTOMB	/usr/include/dlg_config.h	99;"	d
DLG_HAVE_WCURSYNCUP	/usr/include/dlg_config.h	100;"	d
DLG_HAVE_WGETPARENT	/usr/include/dlg_config.h	101;"	d
DLG_HAVE_WGET_WCH	/usr/include/dlg_config.h	102;"	d
DLG_HAVE_WHIPTAIL	/usr/include/dlg_config.h	103;"	d
DLG_HAVE_WSYNCUP	/usr/include/dlg_config.h	104;"	d
DLG_HAVE_XDIALOG	/usr/include/dlg_config.h	105;"	d
DLG_HAVE_XDIALOG2	/usr/include/dlg_config.h	106;"	d
DLG_HAVE__NC_FREE_AND_EXIT	/usr/include/dlg_config.h	107;"	d
DLG_HAVE___ARGZ_COUNT	/usr/include/dlg_config.h	108;"	d
DLG_HAVE___ARGZ_NEXT	/usr/include/dlg_config.h	109;"	d
DLG_HAVE___ARGZ_STRINGIFY	/usr/include/dlg_config.h	110;"	d
DLG_ICONV_CONST	/usr/include/dlg_config.h	111;"	d
DLG_MIXEDCASE_FILENAMES	/usr/include/dlg_config.h	112;"	d
DLG_NCURSES	/usr/include/dlg_config.h	113;"	d
DLG_NEED_WCHAR_H	/usr/include/dlg_config.h	114;"	d
DLG_NLS_TEXTDOMAIN	/usr/include/dlg_config.h	115;"	d
DLG_PACKAGE	/usr/include/dlg_config.h	116;"	d
DLG_RETSIGTYPE	/usr/include/dlg_config.h	117;"	d
DLG_STDC_HEADERS	/usr/include/dlg_config.h	118;"	d
DLG_SYSTEM_NAME	/usr/include/dlg_config.h	119;"	d
DLG_TIME_WITH_SYS_TIME	/usr/include/dlg_config.h	120;"	d
DLG_TYPE_CHTYPE_IS_SCALAR	/usr/include/dlg_config.h	121;"	d
DLG_USE_WIDE_CURSES	/usr/include/dlg_config.h	122;"	d
