!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
_TGMATH_H	/usr/include/tgmath.h	23;"	d
__TGMATH_BINARY_FIRST_REAL_ONLY	/usr/include/tgmath.h	89;"	d
__TGMATH_BINARY_REAL_IMAG	/usr/include/tgmath.h	209;"	d
__TGMATH_BINARY_REAL_ONLY	/usr/include/tgmath.h	97;"	d
__TGMATH_TERNARY_FIRST_SECOND_REAL_ONLY	/usr/include/tgmath.h	115;"	d
__TGMATH_TERNARY_REAL_ONLY	/usr/include/tgmath.h	133;"	d
__TGMATH_UNARY_IMAG	/usr/include/tgmath.h	174;"	d
__TGMATH_UNARY_REAL_IMAG	/usr/include/tgmath.h	160;"	d
__TGMATH_UNARY_REAL_IMAG_RET_REAL	/usr/include/tgmath.h	187;"	d
__TGMATH_UNARY_REAL_ONLY	/usr/include/tgmath.h	73;"	d
__TGMATH_UNARY_REAL_RET_ONLY	/usr/include/tgmath.h	81;"	d
__floating_type	/usr/include/tgmath.h	50;"	d
__floating_type	/usr/include/tgmath.h	55;"	d
__tgmath_real_type	/usr/include/tgmath.h	65;"	d
__tgmath_real_type_sub	/usr/include/tgmath.h	60;"	d
__tgml	/usr/include/tgmath.h	39;"	d
__tgml	/usr/include/tgmath.h	41;"	d
acos	/usr/include/tgmath.h	253;"	d
acosh	/usr/include/tgmath.h	272;"	d
asin	/usr/include/tgmath.h	255;"	d
asinh	/usr/include/tgmath.h	274;"	d
atan	/usr/include/tgmath.h	257;"	d
atan2	/usr/include/tgmath.h	259;"	d
atanh	/usr/include/tgmath.h	276;"	d
carg	/usr/include/tgmath.h	437;"	d
cbrt	/usr/include/tgmath.h	335;"	d
ceil	/usr/include/tgmath.h	341;"	d
cimag	/usr/include/tgmath.h	449;"	d
conj	/usr/include/tgmath.h	440;"	d
copysign	/usr/include/tgmath.h	382;"	d
cos	/usr/include/tgmath.h	262;"	d
cosh	/usr/include/tgmath.h	279;"	d
cproj	/usr/include/tgmath.h	443;"	d
creal	/usr/include/tgmath.h	452;"	d
erf	/usr/include/tgmath.h	385;"	d
erfc	/usr/include/tgmath.h	386;"	d
exp	/usr/include/tgmath.h	289;"	d
exp2	/usr/include/tgmath.h	317;"	d
expm1	/usr/include/tgmath.h	308;"	d
fabs	/usr/include/tgmath.h	344;"	d
fdim	/usr/include/tgmath.h	420;"	d
floor	/usr/include/tgmath.h	347;"	d
fma	/usr/include/tgmath.h	430;"	d
fmax	/usr/include/tgmath.h	423;"	d
fmin	/usr/include/tgmath.h	426;"	d
fmod	/usr/include/tgmath.h	350;"	d
frexp	/usr/include/tgmath.h	292;"	d
hypot	/usr/include/tgmath.h	332;"	d
ilogb	/usr/include/tgmath.h	416;"	d
ldexp	/usr/include/tgmath.h	295;"	d
lgamma	/usr/include/tgmath.h	388;"	d
llrint	/usr/include/tgmath.h	373;"	d
llround	/usr/include/tgmath.h	378;"	d
log	/usr/include/tgmath.h	298;"	d
log10	/usr/include/tgmath.h	302;"	d
log10	/usr/include/tgmath.h	304;"	d
log1p	/usr/include/tgmath.h	311;"	d
log2	/usr/include/tgmath.h	320;"	d
logb	/usr/include/tgmath.h	314;"	d
lrint	/usr/include/tgmath.h	372;"	d
lround	/usr/include/tgmath.h	377;"	d
nearbyint	/usr/include/tgmath.h	354;"	d
nextafter	/usr/include/tgmath.h	396;"	d
nexttoward	/usr/include/tgmath.h	397;"	d
pow	/usr/include/tgmath.h	326;"	d
remainder	/usr/include/tgmath.h	401;"	d
remquo	/usr/include/tgmath.h	367;"	d
rint	/usr/include/tgmath.h	393;"	d
round	/usr/include/tgmath.h	358;"	d
scalb	/usr/include/tgmath.h	405;"	d
scalbln	/usr/include/tgmath.h	412;"	d
scalbn	/usr/include/tgmath.h	409;"	d
sin	/usr/include/tgmath.h	264;"	d
sinh	/usr/include/tgmath.h	281;"	d
sqrt	/usr/include/tgmath.h	329;"	d
tan	/usr/include/tgmath.h	266;"	d
tanh	/usr/include/tgmath.h	283;"	d
tgamma	/usr/include/tgmath.h	387;"	d
trunc	/usr/include/tgmath.h	362;"	d
