!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
COLORS_H_included	/usr/include/dlg_colors.h	28;"	d
DLGC_BG_BORDER	/usr/include/dlg_colors.h	56;"	d
DLGC_BG_BORDER2	/usr/include/dlg_colors.h	60;"	d
DLGC_BG_BUTTON_ACTIVE	/usr/include/dlg_colors.h	64;"	d
DLGC_BG_BUTTON_INACTIVE	/usr/include/dlg_colors.h	68;"	d
DLGC_BG_BUTTON_KEY_ACTIVE	/usr/include/dlg_colors.h	72;"	d
DLGC_BG_BUTTON_KEY_INACTIVE	/usr/include/dlg_colors.h	76;"	d
DLGC_BG_BUTTON_LABEL_ACTIVE	/usr/include/dlg_colors.h	80;"	d
DLGC_BG_BUTTON_LABEL_INACTIVE	/usr/include/dlg_colors.h	84;"	d
DLGC_BG_CHECK	/usr/include/dlg_colors.h	160;"	d
DLGC_BG_CHECK_SELECTED	/usr/include/dlg_colors.h	164;"	d
DLGC_BG_DARROW	/usr/include/dlg_colors.h	172;"	d
DLGC_BG_DIALOG	/usr/include/dlg_colors.h	48;"	d
DLGC_BG_FORM_ACTIVE_TEXT	/usr/include/dlg_colors.h	180;"	d
DLGC_BG_FORM_ITEM_READONLY	/usr/include/dlg_colors.h	88;"	d
DLGC_BG_FORM_TEXT	/usr/include/dlg_colors.h	184;"	d
DLGC_BG_GAUGE	/usr/include/dlg_colors.h	188;"	d
DLGC_BG_INPUTBOX	/usr/include/dlg_colors.h	92;"	d
DLGC_BG_INPUTBOX_BORDER	/usr/include/dlg_colors.h	96;"	d
DLGC_BG_INPUTBOX_BORDER2	/usr/include/dlg_colors.h	100;"	d
DLGC_BG_ITEM	/usr/include/dlg_colors.h	136;"	d
DLGC_BG_ITEMHELP	/usr/include/dlg_colors.h	176;"	d
DLGC_BG_ITEM_SELECTED	/usr/include/dlg_colors.h	140;"	d
DLGC_BG_MENUBOX	/usr/include/dlg_colors.h	124;"	d
DLGC_BG_MENUBOX_BORDER	/usr/include/dlg_colors.h	128;"	d
DLGC_BG_MENUBOX_BORDER2	/usr/include/dlg_colors.h	132;"	d
DLGC_BG_POSITION_INDICATOR	/usr/include/dlg_colors.h	120;"	d
DLGC_BG_SCREEN	/usr/include/dlg_colors.h	40;"	d
DLGC_BG_SEARCHBOX	/usr/include/dlg_colors.h	104;"	d
DLGC_BG_SEARCHBOX_BORDER	/usr/include/dlg_colors.h	112;"	d
DLGC_BG_SEARCHBOX_BORDER2	/usr/include/dlg_colors.h	116;"	d
DLGC_BG_SEARCHBOX_TITLE	/usr/include/dlg_colors.h	108;"	d
DLGC_BG_SHADOW	/usr/include/dlg_colors.h	44;"	d
DLGC_BG_TAG	/usr/include/dlg_colors.h	144;"	d
DLGC_BG_TAG_KEY	/usr/include/dlg_colors.h	152;"	d
DLGC_BG_TAG_KEY_SELECTED	/usr/include/dlg_colors.h	156;"	d
DLGC_BG_TAG_SELECTED	/usr/include/dlg_colors.h	148;"	d
DLGC_BG_TITLE	/usr/include/dlg_colors.h	52;"	d
DLGC_BG_UARROW	/usr/include/dlg_colors.h	168;"	d
DLGC_FG_BORDER	/usr/include/dlg_colors.h	55;"	d
DLGC_FG_BORDER2	/usr/include/dlg_colors.h	59;"	d
DLGC_FG_BUTTON_ACTIVE	/usr/include/dlg_colors.h	63;"	d
DLGC_FG_BUTTON_INACTIVE	/usr/include/dlg_colors.h	67;"	d
DLGC_FG_BUTTON_KEY_ACTIVE	/usr/include/dlg_colors.h	71;"	d
DLGC_FG_BUTTON_KEY_INACTIVE	/usr/include/dlg_colors.h	75;"	d
DLGC_FG_BUTTON_LABEL_ACTIVE	/usr/include/dlg_colors.h	79;"	d
DLGC_FG_BUTTON_LABEL_INACTIVE	/usr/include/dlg_colors.h	83;"	d
DLGC_FG_CHECK	/usr/include/dlg_colors.h	159;"	d
DLGC_FG_CHECK_SELECTED	/usr/include/dlg_colors.h	163;"	d
DLGC_FG_DARROW	/usr/include/dlg_colors.h	171;"	d
DLGC_FG_DIALOG	/usr/include/dlg_colors.h	47;"	d
DLGC_FG_FORM_ACTIVE_TEXT	/usr/include/dlg_colors.h	179;"	d
DLGC_FG_FORM_ITEM_READONLY	/usr/include/dlg_colors.h	87;"	d
DLGC_FG_FORM_TEXT	/usr/include/dlg_colors.h	183;"	d
DLGC_FG_GAUGE	/usr/include/dlg_colors.h	187;"	d
DLGC_FG_INPUTBOX	/usr/include/dlg_colors.h	91;"	d
DLGC_FG_INPUTBOX_BORDER	/usr/include/dlg_colors.h	95;"	d
DLGC_FG_INPUTBOX_BORDER2	/usr/include/dlg_colors.h	99;"	d
DLGC_FG_ITEM	/usr/include/dlg_colors.h	135;"	d
DLGC_FG_ITEMHELP	/usr/include/dlg_colors.h	175;"	d
DLGC_FG_ITEM_SELECTED	/usr/include/dlg_colors.h	139;"	d
DLGC_FG_MENUBOX	/usr/include/dlg_colors.h	123;"	d
DLGC_FG_MENUBOX_BORDER	/usr/include/dlg_colors.h	127;"	d
DLGC_FG_MENUBOX_BORDER2	/usr/include/dlg_colors.h	131;"	d
DLGC_FG_POSITION_INDICATOR	/usr/include/dlg_colors.h	119;"	d
DLGC_FG_SCREEN	/usr/include/dlg_colors.h	39;"	d
DLGC_FG_SEARCHBOX	/usr/include/dlg_colors.h	103;"	d
DLGC_FG_SEARCHBOX_BORDER	/usr/include/dlg_colors.h	111;"	d
DLGC_FG_SEARCHBOX_BORDER2	/usr/include/dlg_colors.h	115;"	d
DLGC_FG_SEARCHBOX_TITLE	/usr/include/dlg_colors.h	107;"	d
DLGC_FG_SHADOW	/usr/include/dlg_colors.h	43;"	d
DLGC_FG_TAG	/usr/include/dlg_colors.h	143;"	d
DLGC_FG_TAG_KEY	/usr/include/dlg_colors.h	151;"	d
DLGC_FG_TAG_KEY_SELECTED	/usr/include/dlg_colors.h	155;"	d
DLGC_FG_TAG_SELECTED	/usr/include/dlg_colors.h	147;"	d
DLGC_FG_TITLE	/usr/include/dlg_colors.h	51;"	d
DLGC_FG_UARROW	/usr/include/dlg_colors.h	167;"	d
DLGC_HL_BORDER	/usr/include/dlg_colors.h	57;"	d
DLGC_HL_BORDER2	/usr/include/dlg_colors.h	61;"	d
DLGC_HL_BUTTON_ACTIVE	/usr/include/dlg_colors.h	65;"	d
DLGC_HL_BUTTON_INACTIVE	/usr/include/dlg_colors.h	69;"	d
DLGC_HL_BUTTON_KEY_ACTIVE	/usr/include/dlg_colors.h	73;"	d
DLGC_HL_BUTTON_KEY_INACTIVE	/usr/include/dlg_colors.h	77;"	d
DLGC_HL_BUTTON_LABEL_ACTIVE	/usr/include/dlg_colors.h	81;"	d
DLGC_HL_BUTTON_LABEL_INACTIVE	/usr/include/dlg_colors.h	85;"	d
DLGC_HL_CHECK	/usr/include/dlg_colors.h	161;"	d
DLGC_HL_CHECK_SELECTED	/usr/include/dlg_colors.h	165;"	d
DLGC_HL_DARROW	/usr/include/dlg_colors.h	173;"	d
DLGC_HL_DIALOG	/usr/include/dlg_colors.h	49;"	d
DLGC_HL_FORM_ACTIVE_TEXT	/usr/include/dlg_colors.h	181;"	d
DLGC_HL_FORM_ITEM_READONLY	/usr/include/dlg_colors.h	89;"	d
DLGC_HL_FORM_TEXT	/usr/include/dlg_colors.h	185;"	d
DLGC_HL_GAUGE	/usr/include/dlg_colors.h	189;"	d
DLGC_HL_INPUTBOX	/usr/include/dlg_colors.h	93;"	d
DLGC_HL_INPUTBOX_BORDER	/usr/include/dlg_colors.h	97;"	d
DLGC_HL_INPUTBOX_BORDER2	/usr/include/dlg_colors.h	101;"	d
DLGC_HL_ITEM	/usr/include/dlg_colors.h	137;"	d
DLGC_HL_ITEMHELP	/usr/include/dlg_colors.h	177;"	d
DLGC_HL_ITEM_SELECTED	/usr/include/dlg_colors.h	141;"	d
DLGC_HL_MENUBOX	/usr/include/dlg_colors.h	125;"	d
DLGC_HL_MENUBOX_BORDER	/usr/include/dlg_colors.h	129;"	d
DLGC_HL_MENUBOX_BORDER2	/usr/include/dlg_colors.h	133;"	d
DLGC_HL_POSITION_INDICATOR	/usr/include/dlg_colors.h	121;"	d
DLGC_HL_SCREEN	/usr/include/dlg_colors.h	41;"	d
DLGC_HL_SEARCHBOX	/usr/include/dlg_colors.h	105;"	d
DLGC_HL_SEARCHBOX_BORDER	/usr/include/dlg_colors.h	113;"	d
DLGC_HL_SEARCHBOX_BORDER2	/usr/include/dlg_colors.h	117;"	d
DLGC_HL_SEARCHBOX_TITLE	/usr/include/dlg_colors.h	109;"	d
DLGC_HL_SHADOW	/usr/include/dlg_colors.h	45;"	d
DLGC_HL_TAG	/usr/include/dlg_colors.h	145;"	d
DLGC_HL_TAG_KEY	/usr/include/dlg_colors.h	153;"	d
DLGC_HL_TAG_KEY_SELECTED	/usr/include/dlg_colors.h	157;"	d
DLGC_HL_TAG_SELECTED	/usr/include/dlg_colors.h	149;"	d
DLGC_HL_TITLE	/usr/include/dlg_colors.h	53;"	d
DLGC_HL_UARROW	/usr/include/dlg_colors.h	169;"	d
__anon1::name	/usr/include/dlg_colors.h	/^    const char *name;$/;"	m	struct:__anon1	access:public
__anon1::value	/usr/include/dlg_colors.h	/^    int value;$/;"	m	struct:__anon1	access:public
color_names_st	/usr/include/dlg_colors.h	/^} color_names_st;$/;"	t	typeref:struct:__anon1
name	/usr/include/dlg_colors.h	/^    const char *name;$/;"	m	struct:__anon1	access:public
value	/usr/include/dlg_colors.h	/^    int value;$/;"	m	struct:__anon1	access:public
