!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
BIG_ENDIAN	/usr/include/endian.h	46;"	d
BYTE_ORDER	/usr/include/endian.h	48;"	d
LITTLE_ENDIAN	/usr/include/endian.h	45;"	d
PDP_ENDIAN	/usr/include/endian.h	47;"	d
_ENDIAN_H	/usr/include/endian.h	19;"	d
__BIG_ENDIAN	/usr/include/endian.h	32;"	d
__FLOAT_WORD_ORDER	/usr/include/endian.h	41;"	d
__LITTLE_ENDIAN	/usr/include/endian.h	31;"	d
__LONG_LONG_PAIR	/usr/include/endian.h	52;"	d
__LONG_LONG_PAIR	/usr/include/endian.h	54;"	d
__PDP_ENDIAN	/usr/include/endian.h	33;"	d
be16toh	/usr/include/endian.h	65;"	d
be16toh	/usr/include/endian.h	81;"	d
be32toh	/usr/include/endian.h	70;"	d
be32toh	/usr/include/endian.h	86;"	d
be64toh	/usr/include/endian.h	75;"	d
be64toh	/usr/include/endian.h	91;"	d
htobe16	/usr/include/endian.h	63;"	d
htobe16	/usr/include/endian.h	79;"	d
htobe32	/usr/include/endian.h	68;"	d
htobe32	/usr/include/endian.h	84;"	d
htobe64	/usr/include/endian.h	73;"	d
htobe64	/usr/include/endian.h	89;"	d
htole16	/usr/include/endian.h	64;"	d
htole16	/usr/include/endian.h	80;"	d
htole32	/usr/include/endian.h	69;"	d
htole32	/usr/include/endian.h	85;"	d
htole64	/usr/include/endian.h	74;"	d
htole64	/usr/include/endian.h	90;"	d
le16toh	/usr/include/endian.h	66;"	d
le16toh	/usr/include/endian.h	82;"	d
le32toh	/usr/include/endian.h	71;"	d
le32toh	/usr/include/endian.h	87;"	d
le64toh	/usr/include/endian.h	76;"	d
le64toh	/usr/include/endian.h	92;"	d
