!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
_PATHS_H_	/usr/include/paths.h	33;"	d
_PATH_BSHELL	/usr/include/paths.h	41;"	d
_PATH_CONSOLE	/usr/include/paths.h	42;"	d
_PATH_CSHELL	/usr/include/paths.h	43;"	d
_PATH_DEFPATH	/usr/include/paths.h	36;"	d
_PATH_DEV	/usr/include/paths.h	69;"	d
_PATH_DEVDB	/usr/include/paths.h	44;"	d
_PATH_DEVNULL	/usr/include/paths.h	45;"	d
_PATH_DRUM	/usr/include/paths.h	46;"	d
_PATH_GSHADOW	/usr/include/paths.h	47;"	d
_PATH_KLOG	/usr/include/paths.h	48;"	d
_PATH_KMEM	/usr/include/paths.h	49;"	d
_PATH_LASTLOG	/usr/include/paths.h	50;"	d
_PATH_MAILDIR	/usr/include/paths.h	51;"	d
_PATH_MAN	/usr/include/paths.h	52;"	d
_PATH_MEM	/usr/include/paths.h	53;"	d
_PATH_MNTTAB	/usr/include/paths.h	54;"	d
_PATH_MOUNTED	/usr/include/paths.h	55;"	d
_PATH_NOLOGIN	/usr/include/paths.h	56;"	d
_PATH_PRESERVE	/usr/include/paths.h	57;"	d
_PATH_RWHODIR	/usr/include/paths.h	58;"	d
_PATH_SENDMAIL	/usr/include/paths.h	59;"	d
_PATH_SHADOW	/usr/include/paths.h	60;"	d
_PATH_SHELLS	/usr/include/paths.h	61;"	d
_PATH_STDPATH	/usr/include/paths.h	38;"	d
_PATH_TMP	/usr/include/paths.h	70;"	d
_PATH_TTY	/usr/include/paths.h	62;"	d
_PATH_UNIX	/usr/include/paths.h	63;"	d
_PATH_UTMP	/usr/include/paths.h	64;"	d
_PATH_VARDB	/usr/include/paths.h	71;"	d
_PATH_VARRUN	/usr/include/paths.h	72;"	d
_PATH_VARTMP	/usr/include/paths.h	73;"	d
_PATH_VI	/usr/include/paths.h	65;"	d
_PATH_WTMP	/usr/include/paths.h	66;"	d
