!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
_STRING_H	/usr/include/string.h	23;"	d
__CORRECT_ISO_CPP_STRING_H_PROTO	/usr/include/string.h	40;"	d
__REDIRECT_NTH	/usr/include/string.h	/^extern int __REDIRECT_NTH (strerror_r,$/;"	p	signature:(strerror_r, (int __errnum, char *__buf, size_t __buflen), __xpg_strerror_r)
__bzero	/usr/include/string.h	/^extern void __bzero (void *__s, size_t __n) __THROW __nonnull ((1));$/;"	p	signature:(void *__s, size_t __n)
__mempcpy	/usr/include/string.h	/^extern void *__mempcpy (void *__restrict __dest,$/;"	p	signature:(void *__restrict __dest, const void *__restrict __src, size_t __n)
__need_NULL	/usr/include/string.h	31;"	d
__need_size_t	/usr/include/string.h	30;"	d
__stpcpy	/usr/include/string.h	/^extern char *__stpcpy (char *__restrict __dest, const char *__restrict __src)$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src)
__stpncpy	/usr/include/string.h	/^extern char *__stpncpy (char *__restrict __dest,$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src, size_t __n)
__strtok_r	/usr/include/string.h	/^extern char *__strtok_r (char *__restrict __s,$/;"	p	signature:(char *__restrict __s, const char *__restrict __delim, char **__restrict __save_ptr)
basename	/usr/include/string.h	/^extern char *basename (const char *__filename) __THROW __nonnull ((1));$/;"	p	signature:(const char *__filename)
bcmp	/usr/include/string.h	/^extern int bcmp (const void *__s1, const void *__s2, size_t __n)$/;"	p	signature:(const void *__s1, const void *__s2, size_t __n)
bcopy	/usr/include/string.h	/^extern void bcopy (const void *__src, void *__dest, size_t __n)$/;"	p	signature:(const void *__src, void *__dest, size_t __n)
bzero	/usr/include/string.h	/^extern void bzero (void *__s, size_t __n) __THROW __nonnull ((1));$/;"	p	signature:(void *__s, size_t __n)
ffs	/usr/include/string.h	/^extern int ffs (int __i) __THROW __attribute__ ((__const__));$/;"	p	signature:(int __i)
ffsl	/usr/include/string.h	/^extern int ffsl (long int __l) __THROW __attribute__ ((__const__));$/;"	p	signature:(long int __l)
ffsll	/usr/include/string.h	/^__extension__ extern int ffsll (long long int __ll)$/;"	p	signature:(long long int __ll)
index	/usr/include/string.h	/^extern char *index (const char *__s, int __c)$/;"	p	signature:(const char *__s, int __c)
index	/usr/include/string.h	/^index (char *__s, int __c) __THROW$/;"	f	signature:(char *__s, int __c)
index	/usr/include/string.h	/^index (const char *__s, int __c) __THROW$/;"	f	signature:(const char *__s, int __c)
memccpy	/usr/include/string.h	/^extern void *memccpy (void *__restrict __dest, const void *__restrict __src,$/;"	p	signature:(void *__restrict __dest, const void *__restrict __src, int __c, size_t __n)
memchr	/usr/include/string.h	/^extern void *memchr (const void *__s, int __c, size_t __n)$/;"	p	signature:(const void *__s, int __c, size_t __n)
memchr	/usr/include/string.h	/^memchr (const void *__s, int __c, size_t __n) __THROW$/;"	f	signature:(const void *__s, int __c, size_t __n)
memchr	/usr/include/string.h	/^memchr (void *__s, int __c, size_t __n) __THROW$/;"	f	signature:(void *__s, int __c, size_t __n)
memcmp	/usr/include/string.h	/^extern int memcmp (const void *__s1, const void *__s2, size_t __n)$/;"	p	signature:(const void *__s1, const void *__s2, size_t __n)
memcpy	/usr/include/string.h	/^extern void *memcpy (void *__restrict __dest, const void *__restrict __src,$/;"	p	signature:(void *__restrict __dest, const void *__restrict __src, size_t __n)
memfrob	/usr/include/string.h	/^extern void *memfrob (void *__s, size_t __n) __THROW __nonnull ((1));$/;"	p	signature:(void *__s, size_t __n)
memmem	/usr/include/string.h	/^extern void *memmem (const void *__haystack, size_t __haystacklen,$/;"	p	signature:(const void *__haystack, size_t __haystacklen, const void *__needle, size_t __needlelen)
memmove	/usr/include/string.h	/^extern void *memmove (void *__dest, const void *__src, size_t __n)$/;"	p	signature:(void *__dest, const void *__src, size_t __n)
mempcpy	/usr/include/string.h	/^extern void *mempcpy (void *__restrict __dest,$/;"	p	signature:(void *__restrict __dest, const void *__restrict __src, size_t __n)
memrchr	/usr/include/string.h	/^extern void *memrchr (const void *__s, int __c, size_t __n)$/;"	p	signature:(const void *__s, int __c, size_t __n)
memset	/usr/include/string.h	/^extern void *memset (void *__s, int __c, size_t __n) __THROW __nonnull ((1));$/;"	p	signature:(void *__s, int __c, size_t __n)
rindex	/usr/include/string.h	/^extern char *rindex (const char *__s, int __c)$/;"	p	signature:(const char *__s, int __c)
rindex	/usr/include/string.h	/^rindex (char *__s, int __c) __THROW$/;"	f	signature:(char *__s, int __c)
rindex	/usr/include/string.h	/^rindex (const char *__s, int __c) __THROW$/;"	f	signature:(const char *__s, int __c)
stpcpy	/usr/include/string.h	/^extern char *stpcpy (char *__restrict __dest, const char *__restrict __src)$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src)
stpncpy	/usr/include/string.h	/^extern char *stpncpy (char *__restrict __dest,$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src, size_t __n)
strcasecmp	/usr/include/string.h	/^extern int strcasecmp (const char *__s1, const char *__s2)$/;"	p	signature:(const char *__s1, const char *__s2)
strcasecmp_l	/usr/include/string.h	/^extern int strcasecmp_l (const char *__s1, const char *__s2,$/;"	p	signature:(const char *__s1, const char *__s2, __locale_t __loc)
strcasestr	/usr/include/string.h	/^extern char *strcasestr (const char *__haystack, const char *__needle)$/;"	p	signature:(const char *__haystack, const char *__needle)
strcat	/usr/include/string.h	/^extern char *strcat (char *__restrict __dest, const char *__restrict __src)$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src)
strchr	/usr/include/string.h	/^strchr (char *__s, int __c) __THROW$/;"	f	signature:(char *__s, int __c)
strchr	/usr/include/string.h	/^strchr (const char *__s, int __c) __THROW$/;"	f	signature:(const char *__s, int __c)
strcmp	/usr/include/string.h	/^extern int strcmp (const char *__s1, const char *__s2)$/;"	p	signature:(const char *__s1, const char *__s2)
strcoll	/usr/include/string.h	/^extern int strcoll (const char *__s1, const char *__s2)$/;"	p	signature:(const char *__s1, const char *__s2)
strcoll_l	/usr/include/string.h	/^extern int strcoll_l (const char *__s1, const char *__s2, __locale_t __l)$/;"	p	signature:(const char *__s1, const char *__s2, __locale_t __l)
strcpy	/usr/include/string.h	/^extern char *strcpy (char *__restrict __dest, const char *__restrict __src)$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src)
strcspn	/usr/include/string.h	/^extern size_t strcspn (const char *__s, const char *__reject)$/;"	p	signature:(const char *__s, const char *__reject)
strdup	/usr/include/string.h	/^extern char *strdup (const char *__s)$/;"	p	signature:(const char *__s)
strdupa	/usr/include/string.h	190;"	d
strerror	/usr/include/string.h	/^extern char *strerror (int __errnum) __THROW;$/;"	p	signature:(int __errnum)
strerror_l	/usr/include/string.h	/^extern char *strerror_l (int __errnum, __locale_t __l) __THROW;$/;"	p	signature:(int __errnum, __locale_t __l)
strfry	/usr/include/string.h	/^extern char *strfry (char *__string) __THROW __nonnull ((1));$/;"	p	signature:(char *__string)
strlen	/usr/include/string.h	/^extern size_t strlen (const char *__s)$/;"	p	signature:(const char *__s)
strncasecmp	/usr/include/string.h	/^extern int strncasecmp (const char *__s1, const char *__s2, size_t __n)$/;"	p	signature:(const char *__s1, const char *__s2, size_t __n)
strncasecmp_l	/usr/include/string.h	/^extern int strncasecmp_l (const char *__s1, const char *__s2,$/;"	p	signature:(const char *__s1, const char *__s2, size_t __n, __locale_t __loc)
strncat	/usr/include/string.h	/^extern char *strncat (char *__restrict __dest, const char *__restrict __src,$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src, size_t __n)
strncmp	/usr/include/string.h	/^extern int strncmp (const char *__s1, const char *__s2, size_t __n)$/;"	p	signature:(const char *__s1, const char *__s2, size_t __n)
strncpy	/usr/include/string.h	/^extern char *strncpy (char *__restrict __dest,$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src, size_t __n)
strndup	/usr/include/string.h	/^extern char *strndup (const char *__string, size_t __n)$/;"	p	signature:(const char *__string, size_t __n)
strndupa	/usr/include/string.h	200;"	d
strnlen	/usr/include/string.h	/^extern size_t strnlen (const char *__string, size_t __maxlen)$/;"	p	signature:(const char *__string, size_t __maxlen)
strpbrk	/usr/include/string.h	/^extern char *strpbrk (const char *__s, const char *__accept)$/;"	p	signature:(const char *__s, const char *__accept)
strpbrk	/usr/include/string.h	/^strpbrk (char *__s, const char *__accept) __THROW$/;"	f	signature:(char *__s, const char *__accept)
strpbrk	/usr/include/string.h	/^strpbrk (const char *__s, const char *__accept) __THROW$/;"	f	signature:(const char *__s, const char *__accept)
strrchr	/usr/include/string.h	/^extern char *strrchr (const char *__s, int __c)$/;"	p	signature:(const char *__s, int __c)
strrchr	/usr/include/string.h	/^strrchr (char *__s, int __c) __THROW$/;"	f	signature:(char *__s, int __c)
strrchr	/usr/include/string.h	/^strrchr (const char *__s, int __c) __THROW$/;"	f	signature:(const char *__s, int __c)
strsep	/usr/include/string.h	/^extern char *strsep (char **__restrict __stringp,$/;"	p	signature:(char **__restrict __stringp, const char *__restrict __delim)
strsignal	/usr/include/string.h	/^extern char *strsignal (int __sig) __THROW;$/;"	p	signature:(int __sig)
strspn	/usr/include/string.h	/^extern size_t strspn (const char *__s, const char *__accept)$/;"	p	signature:(const char *__s, const char *__accept)
strstr	/usr/include/string.h	/^extern char *strstr (const char *__haystack, const char *__needle)$/;"	p	signature:(const char *__haystack, const char *__needle)
strstr	/usr/include/string.h	/^strstr (char *__haystack, const char *__needle) __THROW$/;"	f	signature:(char *__haystack, const char *__needle)
strstr	/usr/include/string.h	/^strstr (const char *__haystack, const char *__needle) __THROW$/;"	f	signature:(const char *__haystack, const char *__needle)
strtok	/usr/include/string.h	/^extern char *strtok (char *__restrict __s, const char *__restrict __delim)$/;"	p	signature:(char *__restrict __s, const char *__restrict __delim)
strtok_r	/usr/include/string.h	/^extern char *strtok_r (char *__restrict __s, const char *__restrict __delim,$/;"	p	signature:(char *__restrict __s, const char *__restrict __delim, char **__restrict __save_ptr)
strverscmp	/usr/include/string.h	/^extern int strverscmp (const char *__s1, const char *__s2)$/;"	p	signature:(const char *__s1, const char *__s2)
strxfrm	/usr/include/string.h	/^extern size_t strxfrm (char *__restrict __dest,$/;"	p	signature:(char *__restrict __dest, const char *__restrict __src, size_t __n)
strxfrm_l	/usr/include/string.h	/^extern size_t strxfrm_l (char *__dest, const char *__src, size_t __n,$/;"	p	signature:(char *__dest, const char *__src, size_t __n, __locale_t __l)
