.TH "std::__future_base::_Ptr" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__future_base::_Ptr \- 
.PP
A \fBunique_ptr\fP based on the instantiating type.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBunique_ptr\fP< _Res, _Result_base::_Deleter > \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Res> struct std::__future_base::_Ptr< _Res >"
A \fBunique_ptr\fP based on the instantiating type. 
.PP
Definition at line 211 of file future.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
