.TH "std::__future_base" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__future_base \- 
.PP
Base class and enclosing scope.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBstd::__basic_future< _Res & >\fP, \fBstd::__basic_future< void >\fP, and \fBstd::__basic_future< _Res >\fP.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_Ptr\fP"
.br
.RI "\fIA \fBunique_ptr\fP based on the instantiating type. \fP"
.ti -1c
.RI "struct \fB_Result\fP"
.br
.RI "\fIResult. \fP"
.ti -1c
.RI "struct \fB_Result< _Res & >\fP"
.br
.RI "\fIPartial specialization for reference types. \fP"
.ti -1c
.RI "struct \fB_Result< void >\fP"
.br
.RI "\fIExplicit specialization for void. \fP"
.ti -1c
.RI "struct \fB_Result_base\fP"
.br
.RI "\fIBase class for results. \fP"
.ti -1c
.RI "class \fB_State\fP"
.br
.RI "\fIShared state between a promise and one or more associated futures. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base class and enclosing scope. 
.PP
Definition at line 136 of file future.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
