.TH "__gnu_parallel::_LexicographicReverse" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_LexicographicReverse \- 
.PP
Compare __a pair of types lexicographically, descending.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbinary_function< _T1, _T2, bool >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _T1 \fBfirst_argument_type\fP"
.br
.ti -1c
.RI "typedef bool \fBresult_type\fP"
.br
.ti -1c
.RI "typedef _T2 \fBsecond_argument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_LexicographicReverse\fP (_Compare &__comp)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBstd::pair\fP< _T1, _T2 > &__p1, const \fBstd::pair\fP< _T1, _T2 > &__p2) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _T1, typename _T2, typename _Compare> class __gnu_parallel::_LexicographicReverse< _T1, _T2, _Compare >"
Compare __a pair of types lexicographically, descending. 
.PP
Definition at line 82 of file multiseq_selection.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef _T1  \fBstd::binary_function\fP< _T1 , _T2 , bool  >::\fBfirst_argument_type\fP\fC [inherited]\fP"
.PP
the type of the first argument /// (no surprises here) 
.PP
Definition at line 114 of file stl_function.h.
.SS "typedef bool  \fBstd::binary_function\fP< _T1 , _T2 , bool  >::\fBresult_type\fP\fC [inherited]\fP"
.PP
type of the return type 
.PP
Definition at line 118 of file stl_function.h.
.SS "typedef _T2  \fBstd::binary_function\fP< _T1 , _T2 , bool  >::\fBsecond_argument_type\fP\fC [inherited]\fP"
.PP
the type of the second argument 
.PP
Definition at line 117 of file stl_function.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
