.TH "__gnu_cxx::random_condition" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::random_condition \- 
.PP
Base class for random probability control and throw.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_cxx::condition_base\fP.
.PP
Inherited by \fB__gnu_cxx::throw_allocator_base< _Tp, random_condition >\fP, and \fB__gnu_cxx::throw_value_base< random_condition >\fP.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBalways_adjustor\fP"
.br
.RI "\fIAlways enter the condition. \fP"
.ti -1c
.RI "struct \fBgroup_adjustor\fP"
.br
.RI "\fIGroup condition. \fP"
.ti -1c
.RI "struct \fBnever_adjustor\fP"
.br
.RI "\fINever enter the condition. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBseed\fP (unsigned long __s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_probability\fP (double __p)"
.br
.ti -1c
.RI "static void \fBthrow_conditionally\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for random probability control and throw. 
.PP
Definition at line 334 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
