.TH "__gnu_cxx::throw_value_limit" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::throw_value_limit \- 
.PP
Type throwing via limit condition.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBthrow_value_base< limit_condition >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBthrow_value_base\fP< \fBlimit_condition\fP > \fBbase_type\fP"
.br
.ti -1c
.RI "typedef \fBlimit_condition\fP \fBcondition_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBthrow_value_limit\fP (const \fBthrow_value_limit\fP &__other)"
.br
.ti -1c
.RI "\fBthrow_value_limit\fP (const std::size_t __i)"
.br
.ti -1c
.RI "\fBthrow_value_base\fP & \fBoperator++\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static size_t & \fBcount\fP ()"
.br
.ti -1c
.RI "static size_t & \fBlimit\fP ()"
.br
.ti -1c
.RI "static void \fBset_limit\fP (const size_t __l)"
.br
.ti -1c
.RI "static void \fBthrow_conditionally\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fB_M_i\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type throwing via limit condition. 
.PP
Definition at line 559 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
