.TH "__gnu_cxx::condition_base" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::condition_base \- 
.PP
Base struct for condition policy.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fB__gnu_cxx::limit_condition\fP, and \fB__gnu_cxx::random_condition\fP.
.SH "Detailed Description"
.PP 
Base struct for condition policy. 

Requires a public member function with the signature void throw_conditionally() 
.PP
Definition at line 253 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
