.TH "__gnu_parallel::_PMWMSSortingData" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_PMWMSSortingData \- 
.PP
Data accessed by all threads.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _TraitsType::difference_type \fB_DifferenceType\fP"
.br
.ti -1c
.RI "typedef \fBstd::iterator_traits\fP< _RAIter > \fB_TraitsType\fP"
.br
.ti -1c
.RI "typedef _TraitsType::value_type \fB_ValueType\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_ThreadIndex\fP \fB_M_num_threads\fP"
.br
.ti -1c
.RI "_DifferenceType * \fB_M_offsets\fP"
.br
.ti -1c
.RI "\fBstd::vector\fP< \fB_Piece\fP< _DifferenceType > > * \fB_M_pieces\fP"
.br
.ti -1c
.RI "_ValueType * \fB_M_samples\fP"
.br
.ti -1c
.RI "_RAIter \fB_M_source\fP"
.br
.ti -1c
.RI "_DifferenceType * \fB_M_starts\fP"
.br
.ti -1c
.RI "_ValueType ** \fB_M_temporary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _RAIter> struct __gnu_parallel::_PMWMSSortingData< _RAIter >"
Data accessed by all threads. 

PMWMS = parallel multiway mergesort 
.PP
Definition at line 61 of file multiway_mergesort.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _RAIter> \fB_ThreadIndex\fP \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_num_threads\fP"
.PP
Number of threads involved. 
.PP
Definition at line 68 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename _RAIter> _DifferenceType* \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_offsets\fP"
.PP
Offsets to add to the found positions. 
.PP
Definition at line 83 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms().
.SS "template<typename _RAIter> \fBstd::vector\fP<\fB_Piece\fP<_DifferenceType> >* \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_pieces\fP"
.PP
Pieces of data to merge \fC\fP[thread][__sequence]. 
.PP
Definition at line 86 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename _RAIter> _ValueType* \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_samples\fP"
.PP
Samples. 
.PP
Definition at line 80 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::__determine_samples(), and __gnu_parallel::parallel_sort_mwms().
.SS "template<typename _RAIter> _RAIter \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_source\fP"
.PP
Input __begin. 
.PP
Definition at line 71 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::__determine_samples(), __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename _RAIter> _DifferenceType* \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_starts\fP"
.PP
Start indices, per thread. 
.PP
Definition at line 74 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::__determine_samples(), __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().
.SS "template<typename _RAIter> _ValueType** \fB__gnu_parallel::_PMWMSSortingData\fP< _RAIter >::\fB_M_temporary\fP"
.PP
Storage in which to sort. 
.PP
Definition at line 77 of file multiway_mergesort.h.
.PP
Referenced by __gnu_parallel::parallel_sort_mwms(), and __gnu_parallel::parallel_sort_mwms_pu().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
