.TH "__gnu_cxx::limit_condition::limit_adjustor" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::limit_condition::limit_adjustor \- 
.PP
Enter the nth condition.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits __gnu_cxx::limit_condition::adjustor_base.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlimit_adjustor\fP (const size_t __l)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enter the nth condition. 
.PP
Definition at line 292 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
