.TH "__gnu_cxx::throw_value_random" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_cxx::throw_value_random \- 
.PP
Type throwing via random condition.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBthrow_value_base< random_condition >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBthrow_value_base\fP< \fBrandom_condition\fP > \fBbase_type\fP"
.br
.ti -1c
.RI "typedef \fBrandom_condition\fP \fBcondition_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBthrow_value_random\fP (const \fBthrow_value_random\fP &__other)"
.br
.ti -1c
.RI "\fBthrow_value_random\fP (const std::size_t __i)"
.br
.ti -1c
.RI "\fBthrow_value_base\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "void \fBseed\fP (unsigned long __s)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_probability\fP (double __p)"
.br
.ti -1c
.RI "static void \fBthrow_conditionally\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fB_M_i\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type throwing via random condition. 
.PP
Definition at line 574 of file throw_allocator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
