.TH "__gnu_parallel::_Nothing" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_Nothing \- 
.PP
Functor doing nothing.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename _It > void \fBoperator()\fP (_It)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functor doing nothing. 

For some __reduction tasks (this is not a function object, but is passed as __selector __dummy parameter. 
.PP
Definition at line 288 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _It > void __gnu_parallel::_Nothing::operator() (_It)\fC [inline]\fP"
.PP
Functor execution. \fBParameters:\fP
.RS 4
\fI__i\fP iterator referencing object. 
.RE
.PP

.PP
Definition at line 294 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
