.TH "__gnu_profile::__vector2list_info" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_profile::__vector2list_info \- 
.PP
A vector-to-list instrumentation line in the object table.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_profile::__object_info_base\fP.
.PP
Inherited by \fB__gnu_profile::__vector2list_stack_info\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__vector2list_info\fP (__stack_t __stack)"
.br
.ti -1c
.RI "\fB__vector2list_info\fP (const \fB__vector2list_info\fP &__o)"
.br
.ti -1c
.RI "const char * \fB__advice\fP () const "
.br
.ti -1c
.RI "bool \fB__is_valid\fP () const "
.br
.ti -1c
.RI "bool \fB__is_valid\fP ()"
.br
.ti -1c
.RI "size_t \fB__iterate\fP ()"
.br
.ti -1c
.RI "float \fB__list_cost\fP ()"
.br
.ti -1c
.RI "float \fB__magnitude\fP () const "
.br
.ti -1c
.RI "void \fB__merge\fP (const \fB__vector2list_info\fP &__o)"
.br
.ti -1c
.RI "void \fB__opr_find\fP (size_t __size)"
.br
.ti -1c
.RI "void \fB__opr_insert\fP (size_t __pos, size_t __num)"
.br
.ti -1c
.RI "void \fB__opr_iterate\fP (size_t __num)"
.br
.ti -1c
.RI "void \fB__resize\fP (size_t __from, size_t __to)"
.br
.ti -1c
.RI "size_t \fB__resize\fP ()"
.br
.ti -1c
.RI "void \fB__set_invalid\fP ()"
.br
.ti -1c
.RI "void \fB__set_list_cost\fP (float __lc)"
.br
.ti -1c
.RI "void \fB__set_vector_cost\fP (float __vc)"
.br
.ti -1c
.RI "size_t \fB__shift_count\fP ()"
.br
.ti -1c
.RI "__stack_t \fB__stack\fP () const "
.br
.ti -1c
.RI "void \fB__write\fP (FILE *__f) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "__stack_t \fB_M_stack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A vector-to-list instrumentation line in the object table. 
.PP
Definition at line 57 of file profiler_vector_to_list.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
