.TH "__gnu_parallel::_PseudoSequenceIterator" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_PseudoSequenceIterator \- 
.PP
_Iterator associated with \fB__gnu_parallel::_PseudoSequence\fP. If features the usual random-access iterator functionality.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _DifferenceTp \fB_DifferenceType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_PseudoSequenceIterator\fP (const _Tp &__val, _DifferenceType __pos)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fB_PseudoSequenceIterator\fP &__i2)"
.br
.ti -1c
.RI "const _Tp & \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fB_PseudoSequenceIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fB_PseudoSequenceIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "_DifferenceType \fBoperator-\fP (const \fB_PseudoSequenceIterator\fP &__i2)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fB_PseudoSequenceIterator\fP &__i2)"
.br
.ti -1c
.RI "const _Tp & \fBoperator[]\fP (_DifferenceType) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _DifferenceTp> class __gnu_parallel::_PseudoSequenceIterator< _Tp, _DifferenceTp >"
_Iterator associated with \fB__gnu_parallel::_PseudoSequence\fP. If features the usual random-access iterator functionality. 

\fBParameters:\fP
.RS 4
\fI_Tp\fP Sequence _M_value type. 
.br
\fI_DifferenceType\fP Sequence difference type. 
.RE
.PP

.PP
Definition at line 306 of file parallel/base.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
