.TH "__gnu_pbds::splay_tree_tag" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::splay_tree_tag \- 
.PP
Splay tree.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_pbds::tree_tag\fP.
.SH "Detailed Description"
.PP 
Splay tree. 
.PP
Definition at line 123 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
