.TH "__gnu_parallel::_SamplingSorter" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_SamplingSorter \- 
.PP
Stable sorting functor.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (_RAIter __first, _RAIter __last, _StrictWeakOrdering __comp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool __stable, class _RAIter, class _StrictWeakOrdering> struct __gnu_parallel::_SamplingSorter< __stable, _RAIter, _StrictWeakOrdering >"
Stable sorting functor. 

Used to reduce code instanciation in multiway_merge_sampling_splitting. 
.PP
Definition at line 1004 of file multiway_merge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
