.TH "__gnu_parallel::__find_if_selector" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::__find_if_selector \- 
.PP
Test predicate on a single element, used for std::find() and std::find_if ().  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_parallel::__generic_find_selector\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename _RAIter1 , typename _RAIter2 , typename _Pred > \fBstd::pair\fP< _RAIter1, _RAIter2 > \fB_M_sequential_algorithm\fP (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred)"
.br
.ti -1c
.RI "template<typename _RAIter1 , typename _RAIter2 , typename _Pred > bool \fBoperator()\fP (_RAIter1 __i1, _RAIter2 __i2, _Pred __pred)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test predicate on a single element, used for std::find() and std::find_if (). 
.PP
Definition at line 50 of file find_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _RAIter1 , typename _RAIter2 , typename _Pred > \fBstd::pair\fP<_RAIter1, _RAIter2> __gnu_parallel::__find_if_selector::_M_sequential_algorithm (_RAIter1 __begin1, _RAIter1 __end1, _RAIter2 __begin2, _Pred __pred)\fC [inline]\fP"
.PP
Corresponding sequential algorithm on a sequence. \fBParameters:\fP
.RS 4
\fI__begin1\fP Begin iterator of first sequence. 
.br
\fI__end1\fP End iterator of first sequence. 
.br
\fI__begin2\fP Begin iterator of second sequence. 
.br
\fI__pred\fP Find predicate. 
.RE
.PP

.PP
Definition at line 72 of file find_selectors.h.
.SS "template<typename _RAIter1 , typename _RAIter2 , typename _Pred > bool __gnu_parallel::__find_if_selector::operator() (_RAIter1 __i1, _RAIter2 __i2, _Pred __pred)\fC [inline]\fP"
.PP
Test on one position. \fBParameters:\fP
.RS 4
\fI__i1\fP _Iterator on first sequence. 
.br
\fI__i2\fP _Iterator on second sequence (unused). 
.br
\fI__pred\fP Find predicate. 
.RE
.PP

.PP
Definition at line 60 of file find_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
