.TH "__gnu_parallel::_LoserTreePointerBase::_Loser" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_LoserTreePointerBase::_Loser \- 
.PP
Internal representation of \fB_LoserTree\fP __elements.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Tp * \fB_M_keyp\fP"
.br
.ti -1c
.RI "int \fB_M_source\fP"
.br
.ti -1c
.RI "bool \fB_M_sup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Compare> struct __gnu_parallel::_LoserTreePointerBase< _Tp, _Compare >::_Loser"
Internal representation of \fB_LoserTree\fP __elements. 
.PP
Definition at line 353 of file losertree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
