.TH "__gnu_pbds::cc_hash_table" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::cc_hash_table \- 
.PP
A concrete collision-chaining hash-based associative container.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbasic_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Resize_Policy, Store_Hash, cc_hash_tag, __gnu_cxx::typelist::create1< Comb_Hash_Fn >::type, Allocator >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Allocator \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef Comb_Hash_Fn \fBcomb_hash_fn\fP"
.br
.ti -1c
.RI "typedef base_type::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef key_rebind::const_pointer \fBconst_key_pointer\fP"
.br
.ti -1c
.RI "typedef key_rebind::const_reference \fBconst_key_reference\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::const_pointer \fBconst_mapped_pointer\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::const_reference \fBconst_mapped_reference\fP"
.br
.ti -1c
.RI "typedef base_type::const_point_iterator \fBconst_point_iterator\fP"
.br
.ti -1c
.RI "typedef value_rebind::const_pointer \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef value_rebind::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef \fBcc_hash_tag\fP \fBcontainer_category\fP"
.br
.ti -1c
.RI "typedef allocator_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef Eq_Fn \fBeq_fn\fP"
.br
.ti -1c
.RI "typedef Hash_Fn \fBhash_fn\fP"
.br
.ti -1c
.RI "typedef base_type::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef key_rebind::pointer \fBkey_pointer\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< key_type >::other \fBkey_rebind\fP"
.br
.ti -1c
.RI "typedef key_rebind::reference \fBkey_reference\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< Key >::other::value_type \fBkey_type\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::pointer \fBmapped_pointer\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< mapped_type >::other \fBmapped_rebind\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::reference \fBmapped_reference\fP"
.br
.ti -1c
.RI "typedef Mapped \fBmapped_type\fP"
.br
.ti -1c
.RI "typedef base_type::point_iterator \fBpoint_iterator\fP"
.br
.ti -1c
.RI "typedef value_rebind::pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef value_rebind::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef Resize_Policy \fBresize_policy\fP"
.br
.ti -1c
.RI "typedef allocator_type::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< value_type >::other \fBvalue_rebind\fP"
.br
.ti -1c
.RI "typedef base_type::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcc_hash_table\fP (const hash_fn &h)"
.br
.ti -1c
.RI "\fBcc_hash_table\fP (const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch)"
.br
.ti -1c
.RI "template<typename It > \fBcc_hash_table\fP (It first, It last, const hash_fn &h, const eq_fn &e)"
.br
.ti -1c
.RI "\fBcc_hash_table\fP (const \fBcc_hash_table\fP &other)"
.br
.ti -1c
.RI "template<typename It > \fBcc_hash_table\fP (It first, It last, const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch, const resize_policy &rp)"
.br
.ti -1c
.RI "template<typename It > \fBcc_hash_table\fP (It first, It last, const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch)"
.br
.ti -1c
.RI "\fBcc_hash_table\fP (const hash_fn &h, const eq_fn &e, const comb_hash_fn &ch, const resize_policy &rp)"
.br
.ti -1c
.RI "template<typename It > \fBcc_hash_table\fP (It first, It last, const hash_fn &h)"
.br
.ti -1c
.RI "template<typename It > \fBcc_hash_table\fP (It first, It last)"
.br
.ti -1c
.RI "\fBcc_hash_table\fP (const hash_fn &h, const eq_fn &e)"
.br
.ti -1c
.RI "\fBcc_hash_table\fP & \fBoperator=\fP (const \fBcc_hash_table\fP &other)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBcc_hash_table\fP &other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, typename Mapped, typename Hash_Fn = typename detail::default_hash_fn<Key>::type, typename Eq_Fn = typename detail::default_eq_fn<Key>::type, typename Comb_Hash_Fn = detail::default_comb_hash_fn::type, typename Resize_Policy = typename detail::default_resize_policy<Comb_Hash_Fn>::type, bool Store_Hash = detail::default_store_hash, typename Allocator = std::allocator<char>> class __gnu_pbds::cc_hash_table< Key, Mapped, Hash_Fn, Eq_Fn, Comb_Hash_Fn, Resize_Policy, Store_Hash, Allocator >"
A concrete collision-chaining hash-based associative container. 
.PP
Definition at line 179 of file assoc_container.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
