.TH "__gnu_pbds::list_update" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::list_update \- 
.PP
A list-update based associative container.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcontainer_base< Key, Mapped, list_update_tag, __gnu_cxx::typelist::create2< Eq_Fn, Update_Policy >::type, Allocator >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Allocator \fBallocator\fP"
.br
.ti -1c
.RI "typedef Allocator \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef base_type::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef key_rebind::const_pointer \fBconst_key_pointer\fP"
.br
.ti -1c
.RI "typedef key_rebind::const_reference \fBconst_key_reference\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::const_pointer \fBconst_mapped_pointer\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::const_reference \fBconst_mapped_reference\fP"
.br
.ti -1c
.RI "typedef base_type::const_point_iterator \fBconst_point_iterator\fP"
.br
.ti -1c
.RI "typedef value_rebind::const_pointer \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef value_rebind::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef \fBlist_update_tag\fP \fBcontainer_category\fP"
.br
.ti -1c
.RI "typedef allocator_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef Eq_Fn \fBeq_fn\fP"
.br
.ti -1c
.RI "typedef base_type::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef key_rebind::pointer \fBkey_pointer\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< key_type >::other \fBkey_rebind\fP"
.br
.ti -1c
.RI "typedef key_rebind::reference \fBkey_reference\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< Key >::other::value_type \fBkey_type\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::pointer \fBmapped_pointer\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< mapped_type >::other \fBmapped_rebind\fP"
.br
.ti -1c
.RI "typedef mapped_rebind::reference \fBmapped_reference\fP"
.br
.ti -1c
.RI "typedef Mapped \fBmapped_type\fP"
.br
.ti -1c
.RI "typedef base_type::point_iterator \fBpoint_iterator\fP"
.br
.ti -1c
.RI "typedef value_rebind::pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef value_rebind::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef allocator_type::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef Update_Policy \fBupdate_policy\fP"
.br
.ti -1c
.RI "typedef allocator_type::template rebind< value_type >::other \fBvalue_rebind\fP"
.br
.ti -1c
.RI "typedef base_type::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename It > \fBlist_update\fP (It first, It last)"
.br
.ti -1c
.RI "\fBlist_update\fP (const \fBlist_update\fP &other)"
.br
.ti -1c
.RI "\fBlist_update\fP & \fBoperator=\fP (const \fBlist_update\fP &other)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBlist_update\fP &other)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, typename Mapped, class Eq_Fn = typename detail::default_eq_fn<Key>::type, class Update_Policy = detail::default_update_policy::type, class Allocator = std::allocator<char>> class __gnu_pbds::list_update< Key, Mapped, Eq_Fn, Update_Policy, Allocator >"
A list-update based associative container. 
.PP
Definition at line 653 of file assoc_container.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
