.TH "__gnu_parallel::_RandomNumber" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_RandomNumber \- 
.PP
Random number generator, based on the Mersenne twister.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_RandomNumber\fP ()"
.br
.ti -1c
.RI "\fB_RandomNumber\fP (uint32_t __seed, uint64_t _M_supremum=0x100000000ULL)"
.br
.ti -1c
.RI "unsigned long \fB__genrand_bits\fP (int __bits)"
.br
.ti -1c
.RI "uint32_t \fBoperator()\fP ()"
.br
.ti -1c
.RI "uint32_t \fBoperator()\fP (uint64_t local_supremum)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Random number generator, based on the Mersenne twister. 
.PP
Definition at line 42 of file random_number.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__gnu_parallel::_RandomNumber::_RandomNumber ()\fC [inline]\fP"
.PP
Default constructor. Seed with 0. 
.PP
Definition at line 74 of file random_number.h.
.SS "__gnu_parallel::_RandomNumber::_RandomNumber (uint32_t __seed, uint64_t _M_supremum = \fC0x100000000ULL\fP)\fC [inline]\fP"
.PP
Constructor. \fBParameters:\fP
.RS 4
\fI__seed\fP Random __seed. 
.br
\fI_M_supremum\fP Generate integer random numbers in the interval \fC\fP[0,_M_supremum). 
.RE
.PP

.PP
Definition at line 85 of file random_number.h.
.SH "Member Function Documentation"
.PP 
.SS "unsigned long __gnu_parallel::_RandomNumber::__genrand_bits (int __bits)\fC [inline]\fP"
.PP
Generate a number of random bits, run-time parameter. \fBParameters:\fP
.RS 4
\fIbits\fP Number of bits to generate. 
.RE
.PP

.PP
Definition at line 109 of file random_number.h.
.SS "uint32_t __gnu_parallel::_RandomNumber::operator() ()\fC [inline]\fP"
.PP
Generate unsigned random 32-bit integer. 
.PP
Definition at line 94 of file random_number.h.
.SS "uint32_t __gnu_parallel::_RandomNumber::operator() (uint64_t local_supremum)\fC [inline]\fP"
.PP
Generate unsigned random 32-bit integer in the interval \fC\fP[0,local_supremum). 
.PP
Definition at line 100 of file random_number.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
