.TH "__gnu_profile::__reentrance_guard" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_profile::__reentrance_guard \- 
.PP
Reentrance guard.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fB__get_in\fP ()"
.br
.ti -1c
.RI "static bool & \fB__inside\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reentrance guard. 

Mechanism to protect all \fB__gnu_profile\fP operations against recursion, multithreaded and exception reentrance. 
.PP
Definition at line 69 of file profiler.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
