.TH "__gnu_profile::__stack_hash" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_profile::__stack_hash \- 
.PP
Hash function for summary trace using call stack as index.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const __stack_t __s) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const __stack_t __stack1, const __stack_t __stack2) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Hash function for summary trace using call stack as index. 
.PP
Definition at line 101 of file profiler_node.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
