.TH "__gnu_pbds::null_mapped_type" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::null_mapped_type \- 
.PP
A mapped-policy indicating that an associative container is a set.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A mapped-policy indicating that an associative container is a set. 
.PP
Definition at line 88 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
