.TH "__gnu_parallel::_Piece" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_Piece \- 
.PP
Subsequence description.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _DifferenceTp \fB_DifferenceType\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_DifferenceType \fB_M_begin\fP"
.br
.ti -1c
.RI "_DifferenceType \fB_M_end\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _DifferenceTp> struct __gnu_parallel::_Piece< _DifferenceTp >"
Subsequence description. 
.PP
Definition at line 46 of file multiway_mergesort.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _DifferenceTp > _DifferenceType \fB__gnu_parallel::_Piece\fP< _DifferenceTp >::\fB_M_begin\fP"
.PP
Begin of subsequence. 
.PP
Definition at line 51 of file multiway_mergesort.h.
.SS "template<typename _DifferenceTp > _DifferenceType \fB__gnu_parallel::_Piece\fP< _DifferenceTp >::\fB_M_end\fP"
.PP
End of subsequence. 
.PP
Definition at line 54 of file multiway_mergesort.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
