.TH "__gnu_sequential" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_sequential \- 
.PP
GNU sequential classes for public use.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
GNU sequential classes for public use. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
