.TH "__gnu_parallel::_QSBThreadLocal" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_QSBThreadLocal \- 
.PP
Information local to one thread in the parallel quicksort run.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _TraitsType::difference_type \fB_DifferenceType\fP"
.br
.ti -1c
.RI "typedef \fBstd::pair\fP< _RAIter, _RAIter > \fB_Piece\fP"
.br
.ti -1c
.RI "typedef \fBstd::iterator_traits\fP< _RAIter > \fB_TraitsType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_QSBThreadLocal\fP (int __queue_size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "volatile _DifferenceType * \fB_M_elements_leftover\fP"
.br
.ti -1c
.RI "\fB_Piece\fP \fB_M_global\fP"
.br
.ti -1c
.RI "\fB_Piece\fP \fB_M_initial\fP"
.br
.ti -1c
.RI "\fB_RestrictedBoundedConcurrentQueue\fP< \fB_Piece\fP > \fB_M_leftover_parts\fP"
.br
.ti -1c
.RI "\fB_ThreadIndex\fP \fB_M_num_threads\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _RAIter> struct __gnu_parallel::_QSBThreadLocal< _RAIter >"
Information local to one thread in the parallel quicksort run. 
.PP
Definition at line 62 of file balanced_quicksort.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _RAIter> typedef \fBstd::pair\fP<_RAIter, _RAIter> \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_Piece\fP"
.PP
Continuous part of the sequence, described by an iterator pair. 
.PP
Definition at line 69 of file balanced_quicksort.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _RAIter> \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_QSBThreadLocal\fP (int __queue_size)\fC [inline]\fP"
.PP
Constructor. \fBParameters:\fP
.RS 4
\fI__queue_size\fP size of the work-stealing queue. 
.RE
.PP

.PP
Definition at line 88 of file balanced_quicksort.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _RAIter> volatile _DifferenceType* \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_M_elements_leftover\fP"
.PP
Pointer to a counter of elements left over to sort. 
.PP
Definition at line 81 of file balanced_quicksort.h.
.PP
Referenced by __gnu_parallel::__qsb_conquer(), and __gnu_parallel::__qsb_local_sort_with_helping().
.SS "template<typename _RAIter> \fB_Piece\fP \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_M_global\fP"
.PP
The complete sequence to sort. 
.PP
Definition at line 84 of file balanced_quicksort.h.
.SS "template<typename _RAIter> \fB_Piece\fP \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_M_initial\fP"
.PP
Initial piece to work on. 
.PP
Definition at line 72 of file balanced_quicksort.h.
.PP
Referenced by __gnu_parallel::__qsb_conquer(), and __gnu_parallel::__qsb_local_sort_with_helping().
.SS "template<typename _RAIter> \fB_RestrictedBoundedConcurrentQueue\fP<\fB_Piece\fP> \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_M_leftover_parts\fP"
.PP
Work-stealing queue. 
.PP
Definition at line 75 of file balanced_quicksort.h.
.PP
Referenced by __gnu_parallel::__qsb_local_sort_with_helping().
.SS "template<typename _RAIter> \fB_ThreadIndex\fP \fB__gnu_parallel::_QSBThreadLocal\fP< _RAIter >::\fB_M_num_threads\fP"
.PP
Number of threads involved in this algorithm. 
.PP
Definition at line 78 of file balanced_quicksort.h.
.PP
Referenced by __gnu_parallel::__qsb_local_sort_with_helping().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
