.TH "__gnu_pbds::pat_trie_tag" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::pat_trie_tag \- 
.PP
PATRICIA trie.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_pbds::trie_tag\fP.
.SH "Detailed Description"
.PP 
PATRICIA trie. 
.PP
Definition at line 132 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
