.TH "__gnu_profile::__hashfunc_stack_info" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_profile::__hashfunc_stack_info \- 
.PP
A hash performance instrumentation line in the stack table.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_profile::__hashfunc_info\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__hashfunc_stack_info\fP (const \fB__hashfunc_info\fP &__o)"
.br
.ti -1c
.RI "const char * \fB__advice\fP () const "
.br
.ti -1c
.RI "void \fB__destruct\fP (size_t __chain, size_t __accesses, size_t __hops)"
.br
.ti -1c
.RI "bool \fB__is_valid\fP () const "
.br
.ti -1c
.RI "float \fB__magnitude\fP () const "
.br
.ti -1c
.RI "void \fB__merge\fP (const \fB__hashfunc_info\fP &__o)"
.br
.ti -1c
.RI "__stack_t \fB__stack\fP () const "
.br
.ti -1c
.RI "void \fB__write\fP (FILE *__f) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "__stack_t \fB_M_stack\fP"
.br
.ti -1c
.RI "bool \fB_M_valid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hash performance instrumentation line in the stack table. 
.PP
Definition at line 104 of file profiler_hash_func.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
