.TH "__gnu_pbds::string_tag" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_pbds::string_tag \- 
.PP
Basic string container, inclusive of strings, ropes, etc.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_pbds::container_tag\fP.
.SH "Detailed Description"
.PP 
Basic string container, inclusive of strings, ropes, etc. 
.PP
Definition at line 96 of file tag_and_trait.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
