.TH "__gnu_parallel::__replace_selector" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::__replace_selector \- 
.PP
std::replace() selector.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_parallel::__generic_for_each_selector< _It >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__replace_selector\fP (const _Tp &\fB__new_val\fP)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (_Tp &__v, _It __i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const _Tp & \fB__new_val\fP"
.br
.ti -1c
.RI "_It \fB_M_finish_iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _It, typename _Tp> struct __gnu_parallel::__replace_selector< _It, _Tp >"
std::replace() selector. 
.PP
Definition at line 132 of file for_each_selectors.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _It , typename _Tp > \fB__gnu_parallel::__replace_selector\fP< _It, _Tp >::\fB__replace_selector\fP (const _Tp & __new_val)\fC [inline, explicit]\fP"
.PP
Constructor. \fBParameters:\fP
.RS 4
\fI__new_val\fP Value to replace with. 
.RE
.PP

.PP
Definition at line 140 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _It , typename _Tp > bool \fB__gnu_parallel::__replace_selector\fP< _It, _Tp >::operator() (_Tp & __v, _It __i)\fC [inline]\fP"
.PP
Functor execution. \fBParameters:\fP
.RS 4
\fI__v\fP Current value. 
.br
\fI__i\fP iterator referencing object. 
.RE
.PP

.PP
Definition at line 146 of file for_each_selectors.h.
.PP
References __gnu_parallel::__replace_selector< _It, _Tp >::__new_val.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _It , typename _Tp > const _Tp& \fB__gnu_parallel::__replace_selector\fP< _It, _Tp >::\fB__new_val\fP"
.PP
Value to replace with. 
.PP
Definition at line 135 of file for_each_selectors.h.
.PP
Referenced by __gnu_parallel::__replace_selector< _It, _Tp >::operator()().
.SS "template<typename _It > _It \fB__gnu_parallel::__generic_for_each_selector\fP< _It >::\fB_M_finish_iterator\fP\fC [inherited]\fP"
.PP
_Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 47 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
