.TH "__gnu_parallel::__generic_find_selector" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::__generic_find_selector \- 
.PP
Base class of all \fB__gnu_parallel::__find_template\fP selectors.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fB__gnu_parallel::__adjacent_find_selector\fP, \fB__gnu_parallel::__find_first_of_selector< _FIterator >\fP, \fB__gnu_parallel::__find_if_selector\fP, and \fB__gnu_parallel::__mismatch_selector\fP.
.SH "Detailed Description"
.PP 
Base class of all \fB__gnu_parallel::__find_template\fP selectors. 
.PP
Definition at line 43 of file find_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
