.TH "__gnu_parallel::_SplitConsistently" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_SplitConsistently \- 
.PP
Split consistently.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<bool __exact, typename _RAIter, typename _Compare, typename _SortingPlacesIterator> struct __gnu_parallel::_SplitConsistently< __exact, _RAIter, _Compare, _SortingPlacesIterator >"
Split consistently. 
.PP
Definition at line 122 of file multiway_mergesort.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
