.TH "__gnu_parallel::__accumulate_binop_reduct" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::__accumulate_binop_reduct \- 
.PP
General reduction, using a binary operator.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__accumulate_binop_reduct\fP (_BinOp &__b)"
.br
.ti -1c
.RI "template<typename _Result , typename _Addend > _Result \fBoperator()\fP (const _Result &__x, const _Addend &__y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_BinOp & \fB__binop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _BinOp> struct __gnu_parallel::__accumulate_binop_reduct< _BinOp >"
General reduction, using a binary operator. 
.PP
Definition at line 335 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
