.TH "__gnu_parallel::__fill_selector" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::__fill_selector \- 
.PP
std::fill() selector.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB__gnu_parallel::__generic_for_each_selector< _It >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename _ValueType > bool \fBoperator()\fP (_ValueType &__v, _It __i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_It \fB_M_finish_iterator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _It> struct __gnu_parallel::__fill_selector< _It >"
std::fill() selector. 
.PP
Definition at line 84 of file for_each_selectors.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _It > template<typename _ValueType > bool \fB__gnu_parallel::__fill_selector\fP< _It >::operator() (_ValueType & __v, _It __i)\fC [inline]\fP"
.PP
Functor execution. \fBParameters:\fP
.RS 4
\fI__v\fP Current value. 
.br
\fI__i\fP iterator referencing object. 
.RE
.PP

.PP
Definition at line 91 of file for_each_selectors.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _It > _It \fB__gnu_parallel::__generic_for_each_selector\fP< _It >::\fB_M_finish_iterator\fP\fC [inherited]\fP"
.PP
_Iterator on last element processed; needed for some algorithms (e. g. std::transform()). 
.PP
Definition at line 47 of file for_each_selectors.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
