.TH "__gnu_parallel::_LoserTreeBase::_Loser" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_LoserTreeBase::_Loser \- 
.PP
Internal representation of a \fB_LoserTree\fP element.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "_Tp \fB_M_key\fP"
.br
.ti -1c
.RI "int \fB_M_source\fP"
.br
.ti -1c
.RI "bool \fB_M_sup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Compare> struct __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::_Loser"
Internal representation of a \fB_LoserTree\fP element. 
.PP
Definition at line 59 of file losertree.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename _Tp , typename _Compare > _Tp \fB__gnu_parallel::_LoserTreeBase\fP< _Tp, _Compare >::\fB_Loser::_M_key\fP"
.PP
_M_key of the element in the \fB_LoserTree\fP. 
.PP
Definition at line 66 of file losertree.h.
.PP
Referenced by __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::__insert_start().
.SS "template<typename _Tp , typename _Compare > int \fB__gnu_parallel::_LoserTreeBase\fP< _Tp, _Compare >::\fB_Loser::_M_source\fP"
.PP
__index of the __source __sequence. 
.PP
Definition at line 64 of file losertree.h.
.PP
Referenced by __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::__get_min_source(), and __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::__insert_start().
.SS "template<typename _Tp , typename _Compare > bool \fB__gnu_parallel::_LoserTreeBase\fP< _Tp, _Compare >::\fB_Loser::_M_sup\fP"
.PP
flag, true iff this is a 'maximum' __sentinel. 
.PP
Definition at line 62 of file losertree.h.
.PP
Referenced by __gnu_parallel::_LoserTreeBase< _Tp, _Compare >::__insert_start().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
