.TH "__gnu_parallel::_LoserTreePointerBase" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__gnu_parallel::_LoserTreePointerBase \- 
.PP
Base class of \fB_Loser\fP Tree implementation using pointers.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fB__gnu_parallel::_LoserTreePointer< __stable, _Tp, _Compare >\fP, and \fB__gnu_parallel::_LoserTreePointer< false, _Tp, _Compare >\fP.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_Loser\fP"
.br
.RI "\fIInternal representation of \fB_LoserTree\fP __elements. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_LoserTreePointerBase\fP (unsigned int __k, _Compare __comp=\fBstd::less\fP< _Tp >())"
.br
.ti -1c
.RI "int \fB__get_min_source\fP ()"
.br
.ti -1c
.RI "void \fB__insert_start\fP (const _Tp &__key, int __source, bool __sup)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "_Compare \fB_M_comp\fP"
.br
.ti -1c
.RI "unsigned int \fB_M_ik\fP"
.br
.ti -1c
.RI "unsigned int \fB_M_k\fP"
.br
.ti -1c
.RI "\fB_Loser\fP * \fB_M_losers\fP"
.br
.ti -1c
.RI "unsigned int \fB_M_offset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, typename _Compare> class __gnu_parallel::_LoserTreePointerBase< _Tp, _Compare >"
Base class of \fB_Loser\fP Tree implementation using pointers. 
.PP
Definition at line 349 of file losertree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
