.TH "std::__is_location_invariant" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__is_location_invariant \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool,(is_pointer< _Tp >::value||is_member_pointer< _Tp >::value)>.
.PP
Inherited by std::__is_location_invariant< _Simple_type_wrapper< _Tp > >.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::__is_location_invariant< _Tp >"
Trait identifying 'location-invariant' types, meaning that the address of the object (or any of its members) will not escape. Also implies a trivial copy constructor and assignment operator. 
.PP
Definition at line 1432 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
