.TH "std::__parallel::_CRandNumber" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__parallel::_CRandNumber \- 
.PP
Functor wrapper for std::rand().  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP (int __limit)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _MustBeInt = int> struct std::__parallel::_CRandNumber< _MustBeInt >"
Functor wrapper for std::rand(). 
.PP
Definition at line 1656 of file algo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
