.TH "std::__profile::unordered_map" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::__profile::unordered_map \- 
.PP
Class \fBstd::unordered_map\fP wrapper with performance instrumentation.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits _GLIBCXX_STD_PR::unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc >.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Base::allocator_type \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef _Base::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef _Base::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef _Base::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef _Base::hasher \fBhasher\fP"
.br
.ti -1c
.RI "typedef _Base::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef _Base::key_equal \fBkey_equal\fP"
.br
.ti -1c
.RI "typedef _Base::key_type \fBkey_type\fP"
.br
.ti -1c
.RI "typedef _Base::mapped_type \fBmapped_type\fP"
.br
.ti -1c
.RI "typedef _Base::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef _Base::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _Base::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunordered_map\fP (size_type __n=10, const hasher &__hf=hasher(), const key_equal &__eql=key_equal(), const allocator_type &__a=allocator_type())"
.br
.ti -1c
.RI "template<typename _InputIterator > \fBunordered_map\fP (_InputIterator __f, _InputIterator __l, size_type __n=10, const hasher &__hf=hasher(), const key_equal &__eql=key_equal(), const allocator_type &__a=allocator_type())"
.br
.ti -1c
.RI "\fBunordered_map\fP (\fBunordered_map\fP &&__x)"
.br
.ti -1c
.RI "\fBunordered_map\fP (\fBinitializer_list\fP< value_type > __l, size_type __n=10, const hasher &__hf=hasher(), const key_equal &__eql=key_equal(), const allocator_type &__a=allocator_type())"
.br
.ti -1c
.RI "\fBunordered_map\fP (const _Base &__x)"
.br
.ti -1c
.RI "_Base & \fB_M_base\fP ()"
.br
.ti -1c
.RI "const _Base & \fB_M_base\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "template<typename _InputIter > void \fBinsert\fP (_InputIter __first, _InputIter __last)"
.br
.ti -1c
.RI "void \fBinsert\fP (const value_type *__first, const value_type *__last)"
.br
.ti -1c
.RI "iterator \fBinsert\fP (const_iterator __iter, const value_type &__v)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBstd::initializer_list\fP< value_type > __l)"
.br
.ti -1c
.RI "\fBstd::pair\fP< iterator, bool > \fBinsert\fP (const value_type &__obj)"
.br
.ti -1c
.RI "\fBunordered_map\fP & \fBoperator=\fP (\fBunordered_map\fP &&__x)"
.br
.ti -1c
.RI "\fBunordered_map\fP & \fBoperator=\fP (\fBinitializer_list\fP< value_type > __l)"
.br
.ti -1c
.RI "\fBunordered_map\fP & \fBoperator=\fP (const \fBunordered_map\fP &__x)"
.br
.ti -1c
.RI "mapped_type & \fBoperator[]\fP (const _Key &_k)"
.br
.ti -1c
.RI "void \fBrehash\fP (size_type __n)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBunordered_map\fP &__x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Key, typename _Tp, typename _Hash = std::hash<_Key>, typename _Pred = std::equal_to<_Key>, typename _Alloc = std::allocator<_Key>> class std::__profile::unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc >"
Class \fBstd::unordered_map\fP wrapper with performance instrumentation. 
.PP
Definition at line 56 of file profile/unordered_map.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
