.TH "std::_Build_index_tuple" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Build_index_tuple \- 
.PP
Builds an \fB_Index_tuple\fP<0, 1, 2, ..., _Num-1>.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fB_Build_index_tuple\fP< _Num-1 >::__type::__next \fB__type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<std::size_t _Num> struct std::_Build_index_tuple< _Num >"
Builds an \fB_Index_tuple\fP<0, 1, 2, ..., _Num-1>. 
.PP
Definition at line 872 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
