.TH "std::_Function_to_function_pointer" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Function_to_function_pointer \- 
.PP
Turns a function type into a function pointer type.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, bool _IsFunctionType = is_function<_Tp>::value> struct std::_Function_to_function_pointer< _Tp, _IsFunctionType >"
Turns a function type into a function pointer type. 
.PP
Definition at line 217 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
