.TH "std::_Fwd_list_node" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Fwd_list_node \- 
.PP
A helper node class for forward_list. This is just a linked list with a data value in each node. There is a sorting utility method.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::_Fwd_list_node_base\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename... _Args> \fB_Fwd_list_node\fP (_Args &&...__args)"
.br
.ti -1c
.RI "void \fB_M_reverse_after\fP ()"
.br
.ti -1c
.RI "\fB_Fwd_list_node_base\fP * \fB_M_transfer_after\fP (\fB_Fwd_list_node_base\fP *__begin, \fB_Fwd_list_node_base\fP *__end)"
.br
.ti -1c
.RI "\fB_Fwd_list_node_base\fP * \fB_M_transfer_after\fP (\fB_Fwd_list_node_base\fP *__begin)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBswap\fP (\fB_Fwd_list_node_base\fP &__x, \fB_Fwd_list_node_base\fP &__y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB_Fwd_list_node_base\fP * \fB_M_next\fP"
.br
.ti -1c
.RI "_Tp \fB_M_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::_Fwd_list_node< _Tp >"
A helper node class for forward_list. This is just a linked list with a data value in each node. There is a sorting utility method. 
.PP
Definition at line 101 of file forward_list.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
