.TH "std::_Index_tuple" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Index_tuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fB_Index_tuple\fP< _Indexes..., sizeof...(_Indexes)> \fB__next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<int... _Indexes> struct std::_Index_tuple< _Indexes >"
Stores a tuple of indices. Used by \fBbind()\fP to extract the elements in a tuple. 
.PP
Definition at line 865 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
