.TH "std::_Placeholder" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::_Placeholder \- 
.PP
The type of placeholder objects defined by libstdc++.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<int _Num> struct std::_Placeholder< _Num >"
The type of placeholder objects defined by libstdc++. 
.PP
Definition at line 804 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
