.TH "std::add_lvalue_reference" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::add_lvalue_reference \- 
.PP
\fBadd_lvalue_reference\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits std::__add_lvalue_reference_helper< _Tp >.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::add_lvalue_reference< _Tp >"
\fBadd_lvalue_reference\fP 
.PP
Definition at line 125 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
