std::chrono
NAME
std::chrono -
ISO C++ 0x entities sub namespace for time and date.
SYNOPSIS
Classes
struct duration
duration
struct duration_values
duration_values
struct system_clock
system_clock
struct time_point
time_point
struct treat_as_floating_point
treat_as_floating_point
Typedefs
typedef system_clock high_resolution_clock
typedef duration< int, ratio< 3600 > > hours
typedef duration< int64_t, micro > microseconds
typedef duration< int64_t, milli > milliseconds
typedef duration< int, ratio< 60 > > minutes
typedef system_clock monotonic_clock
typedef duration< int64_t, nano > nanoseconds
typedef duration< int64_t > seconds
Functions
template<typename _ToDuration , typename _Rep , typename _Period > enable_if< __is_duration< _ToDuration >::value, _ToDuration >::type duration_cast (const duration< _Rep, _Period > &__d)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator!= (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator!= (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > common_type< duration< _Rep1, _Period1 >, duration< _Rep2, _Period2 > >::type operator% (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Rep1 , typename _Period , typename _Rep2 > duration< typename __common_rep_type< _Rep1, typename enable_if<!__is_duration< _Rep2 >::value, _Rep2 >::type >::type, _Period > operator% (const duration< _Rep1, _Period > &__d, const _Rep2 &__s)
template<typename _Rep1 , typename _Period , typename _Rep2 > duration< typename __common_rep_type< _Rep1, _Rep2 >::type, _Period > operator* (const duration< _Rep1, _Period > &__d, const _Rep2 &__s)
template<typename _Rep1 , typename _Period , typename _Rep2 > duration< typename __common_rep_type< _Rep2, _Rep1 >::type, _Period > operator* (const _Rep1 &__s, const duration< _Rep2, _Period > &__d)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > common_type< duration< _Rep1, _Period1 >, duration< _Rep2, _Period2 > >::type operator+ (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Rep2 , typename _Period2 > time_point< _Clock, typename common_type< _Duration1, duration< _Rep2, _Period2 > >::type > operator+ (const time_point< _Clock, _Duration1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Clock , typename _Duration2 > time_point< _Clock, typename common_type< duration< _Rep1, _Period1 >, _Duration2 >::type > operator+ (const duration< _Rep1, _Period1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Rep2 , typename _Period2 > time_point< _Clock, typename common_type< _Duration1, duration< _Rep2, _Period2 > >::type > operator- (const time_point< _Clock, _Duration1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > common_type< _Duration1, _Duration2 >::type operator- (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > common_type< duration< _Rep1, _Period1 >, duration< _Rep2, _Period2 > >::type operator- (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Rep1 , typename _Period , typename _Rep2 > duration< typename __common_rep_type< _Rep1, typename enable_if<!__is_duration< _Rep2 >::value, _Rep2 >::type >::type, _Period > operator/ (const duration< _Rep1, _Period > &__d, const _Rep2 &__s)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > common_type< _Rep1, _Rep2 >::type operator/ (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator< (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator< (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator<= (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator<= (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator== (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator== (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator> (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator> (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _Clock , typename _Duration1 , typename _Duration2 > bool operator>= (const time_point< _Clock, _Duration1 > &__lhs, const time_point< _Clock, _Duration2 > &__rhs)
template<typename _Rep1 , typename _Period1 , typename _Rep2 , typename _Period2 > bool operator>= (const duration< _Rep1, _Period1 > &__lhs, const duration< _Rep2, _Period2 > &__rhs)
template<typename _ToDuration , typename _Clock , typename _Duration > enable_if< __is_duration< _ToDuration >::value, time_point< _Clock, _ToDuration > >::type time_point_cast (const time_point< _Clock, _Duration > &__t)
Detailed Description
ISO C++ 0x entities sub namespace for time and date.
Typedef Documentation
typedef duration<int, ratio<3600> > std::chrono::hours
hours
Definition at line 488 of file chrono.
typedef duration<int64_t, micro> std::chrono::microseconds
microseconds
Definition at line 476 of file chrono.
typedef duration<int64_t, milli> std::chrono::milliseconds
milliseconds
Definition at line 479 of file chrono.
typedef duration<int, ratio< 60> > std::chrono::minutes
minutes
Definition at line 485 of file chrono.
typedef duration<int64_t, nano> std::chrono::nanoseconds
nanoseconds
Definition at line 473 of file chrono.
typedef duration<int64_t > std::chrono::seconds
seconds
Definition at line 482 of file chrono.
Function Documentation
template<typename _ToDuration , typename _Rep , typename _Period > enable_if<__is_duration<_ToDuration>::value, _ToDuration>::type std::chrono::duration_cast (const duration< _Rep, _Period > & __d) [inline]
duration_cast
Definition at line 155 of file chrono.
Referenced by std::this_thread::sleep_for(), and time_point_cast().
template<typename _ToDuration , typename _Clock , typename _Duration > enable_if<__is_duration<_ToDuration>::value, time_point<_Clock, _ToDuration> >::type std::chrono::time_point_cast (const time_point< _Clock, _Duration > & __t) [inline]
time_point_cast
Definition at line 550 of file chrono.
References duration_cast().
Author
Generated automatically by Doxygen for libstdc++ from the source code.