.TH "std::conditional" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::conditional \- 
.PP
conditional  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Iftrue \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool _Cond, typename _Iftrue, typename _Iffalse> struct std::conditional< _Cond, _Iftrue, _Iffalse >"
conditional 
.PP
Definition at line 369 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
