.TH "std::enable_if" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::enable_if \- 
.PP
\fBenable_if\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<bool, typename _Tp = void> struct std::enable_if< bool, _Tp >"
\fBenable_if\fP 
.PP
Definition at line 356 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
