.TH "std::extreme_value_distribution" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::extreme_value_distribution \- 
.PP
A \fBextreme_value_distribution\fP random number distribution.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBparam_type\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _RealType \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBextreme_value_distribution\fP (_RealType __a=_RealType(0), _RealType __b=_RealType(1))"
.br
.ti -1c
.RI "\fBextreme_value_distribution\fP (const \fBparam_type\fP &__p)"
.br
.ti -1c
.RI "_RealType \fBa\fP () const "
.br
.ti -1c
.RI "_RealType \fBb\fP () const "
.br
.ti -1c
.RI "\fBresult_type\fP \fBmax\fP () const "
.br
.ti -1c
.RI "\fBresult_type\fP \fBmin\fP () const "
.br
.ti -1c
.RI "template<typename _UniformRandomNumberGenerator > \fBresult_type\fP \fBoperator()\fP (_UniformRandomNumberGenerator &__urng, const \fBparam_type\fP &__p)"
.br
.ti -1c
.RI "template<typename _UniformRandomNumberGenerator > \fBresult_type\fP \fBoperator()\fP (_UniformRandomNumberGenerator &__urng)"
.br
.ti -1c
.RI "void \fBparam\fP (const \fBparam_type\fP &__param)"
.br
.ti -1c
.RI "\fBparam_type\fP \fBparam\fP () const "
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _RealType = double> class std::extreme_value_distribution< _RealType >"
A \fBextreme_value_distribution\fP random number distribution. 

The formula for the normal probability mass function is \[ p(x|a,b) = \frac{1}{b} \exp( \frac{a-x}{b} - \exp(\frac{a-x}{b})) \] 
.PP
Definition at line 4510 of file random.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _RealType = double> typedef _RealType \fBstd::extreme_value_distribution\fP< _RealType >::\fBresult_type\fP"The type of the range of the distribution. 
.PP
Definition at line 4517 of file random.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _RealType = double> _RealType \fBstd::extreme_value_distribution\fP< _RealType >::a () const\fC [inline]\fP"
.PP
Return the $a$ parameter of the distribution. 
.PP
Definition at line 4568 of file random.h.
.SS "template<typename _RealType = double> _RealType \fBstd::extreme_value_distribution\fP< _RealType >::b () const\fC [inline]\fP"
.PP
Return the $b$ parameter of the distribution. 
.PP
Definition at line 4575 of file random.h.
.SS "template<typename _RealType = double> \fBresult_type\fP \fBstd::extreme_value_distribution\fP< _RealType >::max () const\fC [inline]\fP"
.PP
Returns the least upper bound value of the distribution. 
.PP
Definition at line 4604 of file random.h.
.SS "template<typename _RealType = double> \fBresult_type\fP \fBstd::extreme_value_distribution\fP< _RealType >::min () const\fC [inline]\fP"
.PP
Returns the greatest lower bound value of the distribution. 
.PP
Definition at line 4597 of file random.h.
.SS "template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > \fBresult_type\fP \fBstd::extreme_value_distribution\fP< _RealType >::operator() (_UniformRandomNumberGenerator & __urng)\fC [inline]\fP"
.PP
Generating functions. 
.PP
Definition at line 4612 of file random.h.
.PP
References std::extreme_value_distribution< _RealType >::operator()(), and std::extreme_value_distribution< _RealType >::param().
.PP
Referenced by std::extreme_value_distribution< _RealType >::operator()().
.SS "template<typename _RealType = double> void \fBstd::extreme_value_distribution\fP< _RealType >::param (const \fBparam_type\fP & __param)\fC [inline]\fP"
.PP
Sets the parameter set of the distribution. \fBParameters:\fP
.RS 4
\fI__param\fP The new parameter set of the distribution. 
.RE
.PP

.PP
Definition at line 4590 of file random.h.
.SS "template<typename _RealType = double> \fBparam_type\fP \fBstd::extreme_value_distribution\fP< _RealType >::param () const\fC [inline]\fP"
.PP
Returns the parameter set of the distribution. 
.PP
Definition at line 4582 of file random.h.
.PP
Referenced by std::extreme_value_distribution< _RealType >::operator()(), std::operator==(), and std::operator>>().
.SS "template<typename _RealType = double> void \fBstd::extreme_value_distribution\fP< _RealType >::reset ()\fC [inline]\fP"
.PP
Resets the distribution state. 
.PP
Definition at line 4561 of file random.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
