std::extreme_value_distribution
NAME
std::extreme_value_distribution -
A extreme_value_distribution random number distribution.
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
extreme_value_distribution (_RealType __a=_RealType(0), _RealType __b=_RealType(1))
extreme_value_distribution (const param_type &__p)
_RealType a () const
_RealType b () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
void param (const param_type &__param)
param_type param () const
void reset ()
Detailed Description
template<typename _RealType = double> class std::extreme_value_distribution< _RealType >
A extreme_value_distribution random number distribution.
The formula for the normal probability mass function is \[ p(x|a,b) = \frac{1}{b} \xp( \frac{a-x}{b} - \xp(\frac{a-x}{b})) \]
Definition at line 4510 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::extreme_value_distribution< _RealType >::result_type"The type of the range of the distribution.
Definition at line 4517 of file random.h.
Member Function Documentation
template<typename _RealType = double> _RealType std::extreme_value_distribution< _RealType >::a () const [inline]
Return the $a$ parameter of the distribution.
Definition at line 4568 of file random.h.
template<typename _RealType = double> _RealType std::extreme_value_distribution< _RealType >::b () const [inline]
Return the $b$ parameter of the distribution.
Definition at line 4575 of file random.h.
template<typename _RealType = double> result_type std::extreme_value_distribution< _RealType >::max () const [inline]
Returns the least upper bound value of the distribution.
Definition at line 4604 of file random.h.
template<typename _RealType = double> result_type std::extreme_value_distribution< _RealType >::min () const [inline]
Returns the greatest lower bound value of the distribution.
Definition at line 4597 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::extreme_value_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng) [inline]
Generating functions.
Definition at line 4612 of file random.h.
References std::extreme_value_distribution< _RealType >::operator()(), and std::extreme_value_distribution< _RealType >::param().
Referenced by std::extreme_value_distribution< _RealType >::operator()().
template<typename _RealType = double> void std::extreme_value_distribution< _RealType >::param (const param_type & __param) [inline]
Sets the parameter set of the distribution. Parameters:
__param The new parameter set of the distribution.
Definition at line 4590 of file random.h.
template<typename _RealType = double> param_type std::extreme_value_distribution< _RealType >::param () const [inline]
Returns the parameter set of the distribution.
Definition at line 4582 of file random.h.
Referenced by std::extreme_value_distribution< _RealType >::operator()(), std::operator==(), and std::operator>>().
template<typename _RealType = double> void std::extreme_value_distribution< _RealType >::reset () [inline]
Resets the distribution state.
Definition at line 4561 of file random.h.
Author
Generated automatically by Doxygen for libstdc++ from the source code.