std::gamma_distribution
NAME
std::gamma_distribution -
A gamma continuous distribution for random numbers.
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
gamma_distribution (_RealType __alpha_val=_RealType(1), _RealType __beta_val=_RealType(1))
gamma_distribution (const param_type &__p)
_RealType alpha () const
_RealType beta () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
void param (const param_type &__param)
param_type param () const
void reset ()
Friends
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::gamma_distribution< _RealType1 > &)
template<typename _RealType1 > bool operator== (const std::gamma_distribution< _RealType1 > &__d1, const std::gamma_distribution< _RealType1 > &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::gamma_distribution< _RealType1 > &)
Detailed Description
template<typename _RealType = double> class std::gamma_distribution< _RealType >
A gamma continuous distribution for random numbers.
The formula for the gamma probability density function is: \[ p(x|\alpha,\beta) = \frac{1}{\beta\Gamma(\alpha)} (x/\beta)^{\alpha - 1} e^{-x/\beta} \]
Definition at line 2350 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::gamma_distribution< _RealType >::result_type"The type of the range of the distribution.
Definition at line 2357 of file random.h.
Constructor & Destructor Documentation
template<typename _RealType = double> std::gamma_distribution< _RealType >::gamma_distribution (_RealType __alpha_val = _RealType(1), _RealType __beta_val = _RealType(1)) [inline, explicit]
Constructs a gamma distribution with parameters $\alpha$ and $\beta$.
Definition at line 2402 of file random.h.
Member Function Documentation
template<typename _RealType = double> _RealType std::gamma_distribution< _RealType >::alpha () const [inline]
Returns the $\alpha$ of the distribution.
Definition at line 2423 of file random.h.
template<typename _RealType = double> _RealType std::gamma_distribution< _RealType >::beta () const [inline]
Returns the $\beta$ of the distribution.
Definition at line 2430 of file random.h.
template<typename _RealType = double> result_type std::gamma_distribution< _RealType >::max () const [inline]
Returns the least upper bound value of the distribution.
Definition at line 2459 of file random.h.
Referenced by std::gamma_distribution< result_type >::max().
template<typename _RealType = double> result_type std::gamma_distribution< _RealType >::min () const [inline]
Returns the greatest lower bound value of the distribution.
Definition at line 2452 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::gamma_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng) [inline]
Generating functions.
Definition at line 2467 of file random.h.
Referenced by std::gamma_distribution< result_type >::operator()().
template<typename _RealType > template<typename _UniformRandomNumberGenerator > gamma_distribution< _RealType >::result_type std::gamma_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng, const param_type & __param)"Marsaglia, G. and Tsang, W. W. 'A Simple Method for Generating Gamma Variables' ACM Transactions on Mathematical Software, 26, 3, 363-372, 2000.
Definition at line 1975 of file random.tcc.
References std::log(), and std::pow().
template<typename _RealType = double> void std::gamma_distribution< _RealType >::param (const param_type & __param) [inline]
Sets the parameter set of the distribution. Parameters:
__param The new parameter set of the distribution.
Definition at line 2445 of file random.h.
template<typename _RealType = double> param_type std::gamma_distribution< _RealType >::param () const [inline]
Returns the parameter set of the distribution.
Definition at line 2437 of file random.h.
Referenced by std::gamma_distribution< result_type >::operator()().
template<typename _RealType = double> void std::gamma_distribution< _RealType >::reset () [inline]
Resets the distribution state.
Definition at line 2416 of file random.h.
Referenced by std::negative_binomial_distribution< _IntType >::reset(), std::student_t_distribution< _RealType >::reset(), std::fisher_f_distribution< _RealType >::reset(), and std::chi_squared_distribution< _RealType >::reset().
Friends And Related Function Documentation
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &, const std::gamma_distribution< _RealType1 > &) [friend]
Inserts a gamma_distribution random number distribution __x into the output stream __os. Parameters:
__os An output stream.
__x A gamma_distribution random number distribution.
Returns:
The output stream with the state of __x inserted or in an error state.
template<typename _RealType = double> template<typename _RealType1 > bool operator== (const std::gamma_distribution< _RealType1 > & __d1, const std::gamma_distribution< _RealType1 > & __d2) [friend]
Return true if two gamma distributions have the same parameters and the sequences that would be generated are equal.
Definition at line 2482 of file random.h.
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &, std::gamma_distribution< _RealType1 > &) [friend]
Extracts a gamma_distribution random number distribution __x from the input stream __is. Parameters:
__is An input stream.
__x A gamma_distribution random number generator engine.
Returns:
The input stream with __x extracted or in an error state.
Author
Generated automatically by Doxygen for libstdc++ from the source code.