.TH "std::has_nothrow_copy_constructor" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::has_nothrow_copy_constructor \- 
.PP
\fBhas_nothrow_copy_constructor\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __has_nothrow_copy(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::has_nothrow_copy_constructor< _Tp >"
\fBhas_nothrow_copy_constructor\fP 
.PP
Definition at line 269 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
