.TH "std::has_nothrow_assign" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::has_nothrow_assign \- 
.PP
\fBhas_nothrow_assign\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __has_nothrow_assign(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::has_nothrow_assign< _Tp >"
\fBhas_nothrow_assign\fP 
.PP
Definition at line 275 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
