.TH "std::has_trivial_destructor" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::has_trivial_destructor \- 
.PP
\fBhas_trivial_destructor\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __has_trivial_destructor(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::has_trivial_destructor< _Tp >"
\fBhas_trivial_destructor\fP 
.PP
Definition at line 257 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
