.TH "std::has_trivial_default_constructor" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::has_trivial_default_constructor \- 
.PP
\fBhas_trivial_default_constructor\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __has_trivial_constructor(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::has_trivial_default_constructor< _Tp >"
\fBhas_trivial_default_constructor\fP 
.PP
Definition at line 239 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
