.TH "std::identity" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::identity \- 
.PP
identity  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::identity< _Tp >"
identity 
.PP
Definition at line 44 of file move.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
