.TH "std::independent_bits_engine" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::independent_bits_engine \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _UIntType \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindependent_bits_engine\fP ()"
.br
.ti -1c
.RI "\fBindependent_bits_engine\fP (const _RandomNumberEngine &__rne)"
.br
.ti -1c
.RI "\fBindependent_bits_engine\fP (\fBresult_type\fP __s)"
.br
.ti -1c
.RI "template<typename _Sseq , typename  = typename std::enable_if<!std::is_same<_Sseq, independent_bits_engine>::value		       && !std::is_same<_Sseq, _RandomNumberEngine>::value> ::type> \fBindependent_bits_engine\fP (_Sseq &__q)"
.br
.ti -1c
.RI "\fBindependent_bits_engine\fP (_RandomNumberEngine &&__rne)"
.br
.ti -1c
.RI "const _RandomNumberEngine & \fBbase\fP () const "
.br
.ti -1c
.RI "void \fBdiscard\fP (unsigned long long __z)"
.br
.ti -1c
.RI "\fBresult_type\fP \fBmax\fP () const "
.br
.ti -1c
.RI "\fBresult_type\fP \fBmin\fP () const "
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP ()"
.br
.ti -1c
.RI "void \fBseed\fP (\fBresult_type\fP __s)"
.br
.ti -1c
.RI "template<typename _Sseq > void \fBseed\fP (_Sseq &__q)"
.br
.ti -1c
.RI "void \fBseed\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBindependent_bits_engine\fP &__lhs, const \fBindependent_bits_engine\fP &__rhs)"
.br
.ti -1c
.RI "template<typename _CharT , typename _Traits > \fBstd::basic_istream\fP< _CharT, _Traits > & \fBoperator>>\fP (\fBstd::basic_istream\fP< _CharT, _Traits > &__is, \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType > &__x)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> class std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType >"
Produces random numbers by combining random numbers from some base engine to produce random numbers with a specifies number of bits \fC__w\fP. 
.PP
Definition at line 1010 of file random.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> typedef _UIntType \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBresult_type\fP"The type of the generated random value. 
.PP
Definition at line 1019 of file random.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBindependent_bits_engine\fP ()\fC [inline]\fP"
.PP
Constructs a default independent_bits_engine engine. The underlying engine is default constructed as well. 
.PP
Definition at line 1026 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBindependent_bits_engine\fP (const _RandomNumberEngine & __rne)\fC [inline, explicit]\fP"
.PP
Copy constructs a independent_bits_engine engine. Copies an existing base class random number generator. 
.PP
\fBParameters:\fP
.RS 4
\fIrng\fP An existing (base class) engine object. 
.RE
.PP

.PP
Definition at line 1036 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBindependent_bits_engine\fP (_RandomNumberEngine && __rne)\fC [inline, explicit]\fP"
.PP
Move constructs a independent_bits_engine engine. Copies an existing base class random number generator. 
.PP
\fBParameters:\fP
.RS 4
\fIrng\fP An existing (base class) engine object. 
.RE
.PP

.PP
Definition at line 1046 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBindependent_bits_engine\fP (\fBresult_type\fP __s)\fC [inline, explicit]\fP"
.PP
Seed constructs a independent_bits_engine engine. Constructs the underlying generator engine seeded with \fC__s\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI__s\fP A seed value for the base class engine. 
.RE
.PP

.PP
Definition at line 1056 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> template<typename _Sseq , typename  = typename std::enable_if<!std::is_same<_Sseq, independent_bits_engine>::value		       && !std::is_same<_Sseq, _RandomNumberEngine>::value> ::type> \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBindependent_bits_engine\fP (_Sseq & __q)\fC [inline, explicit]\fP"
.PP
Generator construct a independent_bits_engine engine. \fBParameters:\fP
.RS 4
\fI__q\fP A seed sequence. 
.RE
.PP

.PP
Definition at line 1069 of file random.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> const _RandomNumberEngine& \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::base () const\fC [inline]\fP"
.PP
Gets a const reference to the underlying generator engine object. 
.PP
Definition at line 1104 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> void \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::discard (unsigned long long __z)\fC [inline]\fP"
.PP
Discard a sequence of random numbers. \fBTodo\fP
.RS 4
Look for a faster way to do discard. 
.RE
.PP

.PP
Definition at line 1131 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBresult_type\fP \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::max () const\fC [inline]\fP"
.PP
Gets the maximum value in the generated random number range. \fBTodo\fP
.RS 4
This should be constexpr. 
.RE
.PP

.PP
Definition at line 1122 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> \fBresult_type\fP \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::min () const\fC [inline]\fP"
.PP
Gets the minimum value in the generated random number range. \fBTodo\fP
.RS 4
This should be constexpr. 
.RE
.PP

.PP
Definition at line 1113 of file random.h.
.SS "template<typename _RandomNumberEngine , size_t __w, typename _UIntType > \fBindependent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::\fBresult_type\fP \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::operator() ()"
.PP
Gets the next value in the generated random number sequence. 
.PP
Definition at line 719 of file random.tcc.
.PP
References std::log().
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> template<typename _Sseq > void \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::seed (_Sseq & __q)\fC [inline]\fP"
.PP
Reseeds the independent_bits_engine object with the given seed sequence. \fBParameters:\fP
.RS 4
\fI__q\fP A seed generator function. 
.RE
.PP

.PP
Definition at line 1096 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> void \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::seed (\fBresult_type\fP __s)\fC [inline]\fP"
.PP
Reseeds the independent_bits_engine object with the default seed for the underlying base class generator engine. 
.PP
Definition at line 1086 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> void \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType >::seed ()\fC [inline]\fP"
.PP
Reseeds the independent_bits_engine object with the default seed for the underlying base class generator engine. 
.PP
Definition at line 1078 of file random.h.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> bool operator== (const \fBindependent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType > & __lhs, const \fBindependent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType > & __rhs)\fC [friend]\fP"
.PP
Compares two independent_bits_engine random number generator objects of the same type for equality. \fBParameters:\fP
.RS 4
\fI__lhs\fP A independent_bits_engine random number generator object. 
.br
\fI__rhs\fP Another independent_bits_engine random number generator object.
.RE
.PP
\fBReturns:\fP
.RS 4
true if the infinite sequences of generated values would be equal, false otherwise. 
.RE
.PP

.PP
Definition at line 1156 of file random.h.
.SS "template<typename _RandomNumberEngine, size_t __w, typename _UIntType> template<typename _CharT , typename _Traits > \fBstd::basic_istream\fP<_CharT, _Traits>& operator>> (\fBstd::basic_istream\fP< _CharT, _Traits > & __is, \fBstd::independent_bits_engine\fP< _RandomNumberEngine, __w, _UIntType > & __x)\fC [friend]\fP"
.PP
Extracts the current state of a % subtract_with_carry_engine random number generator engine \fC__x\fP from the input stream \fC__is\fP. \fBParameters:\fP
.RS 4
\fI__is\fP An input stream. 
.br
\fI__x\fP A independent_bits_engine random number generator engine.
.RE
.PP
\fBReturns:\fP
.RS 4
The input stream with the state of \fC__x\fP extracted or in an error state. 
.RE
.PP

.PP
Definition at line 1174 of file random.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
