.TH "std::indirect_array" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::indirect_array \- 
.PP
Reference to arbitrary subset of an array.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindirect_array\fP (const \fBindirect_array\fP &)"
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator%=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator%=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator&=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator&=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator*=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator*=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator+=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator+=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator-=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator-=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator/=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator/=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator<<=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator<<=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator=\fP (const _Tp &) const "
.br
.ti -1c
.RI "\fBindirect_array\fP & \fBoperator=\fP (const \fBindirect_array\fP &)"
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator>>=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator>>=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator^=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator^=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "void \fBoperator|=\fP (const \fBvalarray\fP< _Tp > &) const "
.br
.ti -1c
.RI "template<class _Dom > void \fBoperator|=\fP (const _Expr< _Dom, _Tp > &) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBgslice_array< _Tp >\fP"
.br
.ti -1c
.RI "class \fBvalarray< _Tp >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _Tp> class std::indirect_array< _Tp >"
Reference to arbitrary subset of an array. 

An \fBindirect_array\fP is a reference to the actual elements of an array specified by an ordered array of indices. The way to get an \fBindirect_array\fP is to call operator[](valarray<size_t>) on a valarray. The returned \fBindirect_array\fP then permits carrying operations out on the referenced subset of elements in the original valarray.
.PP
For example, if an \fBindirect_array\fP is obtained using the array (4,2,0) as an argument, and then assigned to an array containing (1,2,3), then the underlying array will have array[0]==3, array[2]==2, and array[4]==1.
.PP
\fBParameters:\fP
.RS 4
\fITp\fP Element type. 
.RE
.PP

.PP
Definition at line 61 of file indirect_array.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator%= (const \fBvalarray\fP< _Tp > &) const"
.PP
Modulo slice elements by corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator&= (const \fBvalarray\fP< _Tp > &) const"
.PP
Logical and slice elements with corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator*= (const \fBvalarray\fP< _Tp > &) const"
.PP
Multiply slice elements by corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator+= (const \fBvalarray\fP< _Tp > &) const"
.PP
Add corresponding elements of \fIv\fP to slice elements. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator-= (const \fBvalarray\fP< _Tp > &) const"
.PP
Subtract corresponding elements of \fIv\fP from slice elements. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator/= (const \fBvalarray\fP< _Tp > &) const"
.PP
Divide slice elements by corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator<<= (const \fBvalarray\fP< _Tp > &) const"
.PP
Left shift slice elements by corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator>>= (const \fBvalarray\fP< _Tp > &) const"
.PP
Right shift slice elements by corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator^= (const \fBvalarray\fP< _Tp > &) const"
.PP
Logical xor slice elements with corresponding elements of \fIv\fP. 
.SS "template<class _Tp> void \fBstd::indirect_array\fP< _Tp >::operator|= (const \fBvalarray\fP< _Tp > &) const"
.PP
Logical or slice elements with corresponding elements of \fIv\fP. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
