.TH "std::initializer_list" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::initializer_list \- 
.PP
\fBinitializer_list\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const _E * \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef const _E & \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef const _E * \fBiterator\fP"
.br
.ti -1c
.RI "typedef const _E & \fBreference\fP"
.br
.ti -1c
.RI "typedef size_t \fBsize_type\fP"
.br
.ti -1c
.RI "typedef _E \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const_iterator \fBbegin\fP () const "
.br
.ti -1c
.RI "const_iterator \fBend\fP () const "
.br
.ti -1c
.RI "size_type \fBsize\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class _E> class std::initializer_list< _E >"
\fBinitializer_list\fP 
.PP
Definition at line 45 of file initializer_list.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
