.TH "std::is_base_of" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_base_of \- 
.PP
\fBis_base_of\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_base_of(_Base, _Derived)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Base, typename _Derived> struct std::is_base_of< _Base, _Derived >"
\fBis_base_of\fP 
.PP
Definition at line 283 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
