.TH "std::is_bind_expression" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_bind_expression \- 
.PP
Determines if the given type _Tp is a function object should be treated as a subexpression when evaluating calls to function objects returned by \fBbind()\fP. [TR1 3.6.1].  

.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_bind_expression< _Tp >"
Determines if the given type _Tp is a function object should be treated as a subexpression when evaluating calls to function objects returned by \fBbind()\fP. [TR1 3.6.1]. 
.PP
Definition at line 790 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
