.TH "std::is_convertible" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_convertible \- 
.PP
\fBis_convertible\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_convertible_helper< _From, _To >::__value >.
.SH "Detailed Description"
.PP 

.SS "template<typename _From, typename _To> struct std::is_convertible< _From, _To >"
\fBis_convertible\fP 
.PP
Definition at line 309 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
