.TH "std::is_error_code_enum" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_error_code_enum \- 
.PP
\fBis_error_code_enum\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits false_type.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_error_code_enum< _Tp >"
\fBis_error_code_enum\fP 
.PP
Definition at line 52 of file system_error.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
