.TH "std::is_explicitly_convertible" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_explicitly_convertible \- 
.PP
\fBis_explicitly_convertible\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBis_constructible< _To, _From >\fP.
.SH "Detailed Description"
.PP 

.SS "template<typename _From, typename _To> struct std::is_explicitly_convertible< _From, _To >"
\fBis_explicitly_convertible\fP 
.PP
Definition at line 316 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
