.TH "std::is_pod" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_pod \- 
.PP
\fBis_pod\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_pod(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_pod< _Tp >"
\fBis_pod\fP 
.PP
Definition at line 191 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
