.TH "std::is_placeholder" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_placeholder \- 
.PP
Determines if the given type _Tp is a placeholder in a \fBbind()\fP expression and, if so, which placeholder it is. [TR1 3.6.2].  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< int, 0 >.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_placeholder< _Tp >"
Determines if the given type _Tp is a placeholder in a \fBbind()\fP expression and, if so, which placeholder it is. [TR1 3.6.2]. 
.PP
Definition at line 799 of file functional.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
