.TH "std::is_reference" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_reference \- 
.PP
\fBis_reference\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool,(is_lvalue_reference< _Tp >::value||is_rvalue_reference< _Tp >::value)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_reference< _Tp >"
\fBis_reference\fP 
.PP
Definition at line 89 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
