.TH "std::is_standard_layout" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_standard_layout \- 
.PP
\fBis_standard_layout\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_standard_layout(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_standard_layout< _Tp >"
\fBis_standard_layout\fP 
.PP
Definition at line 184 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
