.TH "std::is_signed" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_signed \- 
.PP
\fBis_signed\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_signed_helper< _Tp >::value >.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_signed< _Tp >"
\fBis_signed\fP 
.PP
Definition at line 163 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
