.TH "std::is_trivial" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_trivial \- 
.PP
\fBis_trivial\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, __is_trivial(_Tp)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_trivial< _Tp >"
\fBis_trivial\fP 
.PP
Definition at line 178 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
