.TH "std::is_unsigned" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::is_unsigned \- 
.PP
\fBis_unsigned\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool,(is_arithmetic< _Tp >::value &&!is_signed< _Tp >::value)>.
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::is_unsigned< _Tp >"
\fBis_unsigned\fP 
.PP
Definition at line 169 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
