std::lognormal_distribution
NAME
std::lognormal_distribution -
A lognormal_distribution random number distribution.
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
lognormal_distribution (_RealType __m=_RealType(0), _RealType __s=_RealType(1))
lognormal_distribution (const param_type &__p)
_RealType m () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
void param (const param_type &__param)
param_type param () const
void reset ()
_RealType s () const
Friends
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::lognormal_distribution< _RealType1 > &)
template<typename _RealType1 > bool operator== (const std::lognormal_distribution< _RealType1 > &__d1, const std::lognormal_distribution< _RealType1 > &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::lognormal_distribution< _RealType1 > &)
Detailed Description
template<typename _RealType = double> class std::lognormal_distribution< _RealType >
A lognormal_distribution random number distribution.
The formula for the normal probability mass function is \[ p(x|m,s) = \frac{1}{sx\sqrt{2\pi}} \xp{-\frac{(\ln{x} - m)^2}{2s^2}} \]
Definition at line 2174 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::lognormal_distribution< _RealType >::result_type"The type of the range of the distribution.
Definition at line 2181 of file random.h.
Member Function Documentation
template<typename _RealType = double> result_type std::lognormal_distribution< _RealType >::max () const [inline]
Returns the least upper bound value of the distribution.
Definition at line 2265 of file random.h.
template<typename _RealType = double> result_type std::lognormal_distribution< _RealType >::min () const [inline]
Returns the greatest lower bound value of the distribution.
Definition at line 2258 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::lognormal_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng) [inline]
Generating functions.
Definition at line 2273 of file random.h.
References std::lognormal_distribution< _RealType >::operator()(), and std::lognormal_distribution< _RealType >::param().
Referenced by std::lognormal_distribution< _RealType >::operator()().
template<typename _RealType = double> void std::lognormal_distribution< _RealType >::param (const param_type & __param) [inline]
Sets the parameter set of the distribution. Parameters:
__param The new parameter set of the distribution.
Definition at line 2251 of file random.h.
template<typename _RealType = double> param_type std::lognormal_distribution< _RealType >::param () const [inline]
Returns the parameter set of the distribution.
Definition at line 2243 of file random.h.
Referenced by std::lognormal_distribution< _RealType >::operator()().
template<typename _RealType = double> void std::lognormal_distribution< _RealType >::reset () [inline]"Resets the distribution state.
Definition at line 2225 of file random.h.
References std::normal_distribution< _RealType >::reset().
Friends And Related Function Documentation
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream<_CharT, _Traits>& operator<< (std::basic_ostream< _CharT, _Traits > &, const std::lognormal_distribution< _RealType1 > &) [friend]
Inserts a lognormal_distribution random number distribution __x into the output stream __os. Parameters:
__os An output stream.
__x A lognormal_distribution random number distribution.
Returns:
The output stream with the state of __x inserted or in an error state.
template<typename _RealType = double> template<typename _RealType1 > bool operator== (const std::lognormal_distribution< _RealType1 > & __d1, const std::lognormal_distribution< _RealType1 > & __d2) [friend]
Return true if two lognormal distributions have the same parameters and the sequences that would be generated are equal.
Definition at line 2289 of file random.h.
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream<_CharT, _Traits>& operator>> (std::basic_istream< _CharT, _Traits > &, std::lognormal_distribution< _RealType1 > &) [friend]
Extracts a lognormal_distribution random number distribution __x from the input stream __is. Parameters:
__is An input stream.
__x A lognormal_distribution random number generator engine.
Returns:
The input stream with __x extracted or in an error state.
Author
Generated automatically by Doxygen for libstdc++ from the source code.