.TH "std::make_unsigned" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::make_unsigned \- 
.PP
\fBmake_unsigned\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef __make_unsigned_selector< _Tp >::__type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::make_unsigned< _Tp >"
\fBmake_unsigned\fP 
.PP
Definition at line 510 of file type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
