.TH "std::normal_distribution::param_type" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::normal_distribution::param_type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBnormal_distribution\fP< _RealType > \fBdistribution_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBparam_type\fP (_RealType __mean=_RealType(0), _RealType __stddev=_RealType(1))"
.br
.ti -1c
.RI "_RealType \fBmean\fP () const "
.br
.ti -1c
.RI "_RealType \fBstddev\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBparam_type\fP &__p1, const \fBparam_type\fP &__p2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _RealType = double> struct std::normal_distribution< _RealType >::param_type"
Parameter type. 
.PP
Definition at line 1999 of file random.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
