.TH "std::ostreambuf_iterator" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ostreambuf_iterator \- 
.PP
Provides output iterator semantics for streambufs.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBiterator< output_iterator_tag, void, void, void, void >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef \fBoutput_iterator_tag\fP \fBiterator_category\fP"
.br
.ti -1c
.RI "typedef void \fBpointer\fP"
.br
.ti -1c
.RI "typedef void \fBreference\fP"
.br
.ti -1c
.RI "typedef void \fBvalue_type\fP"
.br
.in -1c
.PP
.RI "\fB\fP"
.br
 
.PP
.in +1c
.in +1c
.ti -1c
.RI "typedef _CharT \fBchar_type\fP"
.br
.ti -1c
.RI "typedef _Traits \fBtraits_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_streambuf\fP< _CharT, _Traits > \fBstreambuf_type\fP"
.br
.ti -1c
.RI "typedef \fBbasic_ostream\fP< _CharT, _Traits > \fBostream_type\fP"
.br
.in -1c
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBostreambuf_iterator\fP (\fBostream_type\fP &__s)  throw ()"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP (\fBstreambuf_type\fP *__s)  throw ()"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP & \fB_M_put\fP (const _CharT *__ws, \fBstreamsize\fP __len)"
.br
.ti -1c
.RI "bool \fBfailed\fP () const   throw ()"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP & \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBostreambuf_iterator\fP & \fBoperator=\fP (_CharT __c)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename _CharT2 > __gnu_cxx::__enable_if< __is_char< _CharT2 >::__value, \fBostreambuf_iterator\fP< _CharT2 > >::__type \fBcopy\fP (\fBistreambuf_iterator\fP< _CharT2 >, \fBistreambuf_iterator\fP< _CharT2 >, \fBostreambuf_iterator\fP< _CharT2 >)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _CharT, typename _Traits> class std::ostreambuf_iterator< _CharT, _Traits >"
Provides output iterator semantics for streambufs. 
.PP
Definition at line 204 of file streambuf_iterator.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > typedef _CharT \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBchar_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 211 of file streambuf_iterator.h.
.SS "typedef void  \fBstd::iterator\fP< \fBoutput_iterator_tag\fP , void , void , void , void  >::\fBdifference_type\fP\fC [inherited]\fP"
.PP
Distance between iterators is represented as this type. 
.PP
Definition at line 121 of file stl_iterator_base_types.h.
.SS "typedef \fBoutput_iterator_tag\fP  \fBstd::iterator\fP< \fBoutput_iterator_tag\fP , void , void , void , void  >::\fBiterator_category\fP\fC [inherited]\fP"
.PP
One of the \fBtag types\fP. 
.PP
Definition at line 117 of file stl_iterator_base_types.h.
.SS "template<typename _CharT , typename _Traits > typedef \fBbasic_ostream\fP<_CharT, _Traits> \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBostream_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 214 of file streambuf_iterator.h.
.SS "typedef void  \fBstd::iterator\fP< \fBoutput_iterator_tag\fP , void , void , void , void  >::\fBpointer\fP\fC [inherited]\fP"
.PP
This type represents a pointer-to-value_type. 
.PP
Definition at line 123 of file stl_iterator_base_types.h.
.SS "typedef void  \fBstd::iterator\fP< \fBoutput_iterator_tag\fP , void , void , void , void  >::\fBreference\fP\fC [inherited]\fP"
.PP
This type represents a reference-to-value_type. 
.PP
Definition at line 125 of file stl_iterator_base_types.h.
.SS "template<typename _CharT , typename _Traits > typedef \fBbasic_streambuf\fP<_CharT, _Traits> \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBstreambuf_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 213 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > typedef _Traits \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBtraits_type\fP"
.PP
Public typedefs. 
.PP
Definition at line 212 of file streambuf_iterator.h.
.SS "typedef void  \fBstd::iterator\fP< \fBoutput_iterator_tag\fP , void , void , void , void  >::\fBvalue_type\fP\fC [inherited]\fP"
.PP
The type 'pointed to' by the iterator. 
.PP
Definition at line 119 of file stl_iterator_base_types.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBostreambuf_iterator\fP (\fBostream_type\fP & __s)  throw ()\fC [inline]\fP"
.PP
Construct output iterator from ostream. 
.PP
Definition at line 229 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::\fBostreambuf_iterator\fP (\fBstreambuf_type\fP * __s)  throw ()\fC [inline]\fP"
.PP
Construct output iterator from streambuf. 
.PP
Definition at line 233 of file streambuf_iterator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _CharT , typename _Traits > bool \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::failed () const  throw ()\fC [inline]\fP"
.PP
Return true if previous \fBoperator=()\fP failed. 
.PP
Definition at line 263 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBostreambuf_iterator\fP& \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::operator* ()\fC [inline]\fP"
.PP
Return *this. 
.PP
Definition at line 248 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBostreambuf_iterator\fP& \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::operator++ ()\fC [inline]\fP"
.PP
Return *this. 
.PP
Definition at line 258 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBostreambuf_iterator\fP& \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::operator++ (int)\fC [inline]\fP"
.PP
Return *this. 
.PP
Definition at line 253 of file streambuf_iterator.h.
.SS "template<typename _CharT , typename _Traits > \fBostreambuf_iterator\fP& \fBstd::ostreambuf_iterator\fP< _CharT, _Traits >::operator= (_CharT __c)\fC [inline]\fP"
.PP
Write character to streambuf. Calls \fBstreambuf.sputc()\fP. 
.PP
Definition at line 238 of file streambuf_iterator.h.
.PP
References std::basic_streambuf< _CharT, _Traits >::sputc().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
