.TH "std::placeholders" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::placeholders \- 
.PP
ISO C++ 0x entities sub namespace for functional.
.PP
Define a large number of placeholders. There is no way to simplify this with variadic templates, because we're introducing unique names for each.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
ISO C++ 0x entities sub namespace for functional.
.PP
Define a large number of placeholders. There is no way to simplify this with variadic templates, because we're introducing unique names for each. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
