.TH "std::promise" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::promise \- 
.PP
Primary template for promise.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpromise\fP (\fBpromise\fP &&__rhs)"
.br
.ti -1c
.RI "\fBpromise\fP (const \fBpromise\fP &)"
.br
.ti -1c
.RI "\fBfuture\fP< _Res > \fBget_future\fP ()"
.br
.ti -1c
.RI "\fBpromise\fP & \fBoperator=\fP (\fBpromise\fP &&__rhs)"
.br
.ti -1c
.RI "\fBpromise\fP & \fBoperator=\fP (const \fBpromise\fP &)"
.br
.ti -1c
.RI "void \fBset_exception\fP (exception_ptr __p)"
.br
.ti -1c
.RI "void \fBset_value\fP (const _Res &__r)"
.br
.ti -1c
.RI "void \fBset_value\fP (_Res &&__r)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBpromise\fP &__rhs)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fB_State::_Setter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Res> class std::promise< _Res >"
Primary template for promise. 
.PP
Definition at line 825 of file future.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
