.TH "std::random_access_iterator_tag" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::random_access_iterator_tag \- 
.PP
Random-access iterators support a superset of bidirectional /// iterator operations.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::bidirectional_iterator_tag\fP.
.SH "Detailed Description"
.PP 
Random-access iterators support a superset of bidirectional /// iterator operations. 
.PP
Definition at line 99 of file stl_iterator_base_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
