.TH "std::ratio_divide" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_divide \- 
.PP
\fBratio_divide\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBratio_multiply\fP< _R1, \fBratio\fP< _R2::den, _R2::num > >::\fBtype\fP \fBtype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic_assert\fP (_R2::num!=0,'division by 0')"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_divide< _R1, _R2 >"
\fBratio_divide\fP 
.PP
Definition at line 216 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
