.TH "std::ratio_greater" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_greater \- 
.PP
\fBratio_greater\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, ratio_less< _R2, _R1 >::value >.
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_greater< _R1, _R2 >"
\fBratio_greater\fP 
.PP
Definition at line 269 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
