.TH "std::ratio_not_equal" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_not_equal \- 
.PP
\fBratio_not_equal\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool,!ratio_equal< _R1, _R2 >::value >.
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_not_equal< _R1, _R2 >"
\fBratio_not_equal\fP 
.PP
Definition at line 233 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
