.TH "std::ratio_subtract" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::ratio_subtract \- 
.PP
\fBratio_subtract\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBratio_add\fP< _R1, \fBratio\fP<-_R2::num, _R2::den > >::\fBtype\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _R1, typename _R2> struct std::ratio_subtract< _R1, _R2 >"
\fBratio_subtract\fP 
.PP
Definition at line 189 of file ratio.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
