.TH "std::seed_seq" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::seed_seq \- 
.PP
The \fBseed_seq\fP class generates sequences of seeds for random number generators.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef uint_least32_t \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBseed_seq\fP ()"
.br
.ti -1c
.RI "template<typename _IntType > \fBseed_seq\fP (\fBstd::initializer_list\fP< _IntType > il)"
.br
.ti -1c
.RI "template<typename _InputIterator > \fBseed_seq\fP (_InputIterator __begin, _InputIterator __end)"
.br
.ti -1c
.RI "template<typename _RandomAccessIterator > void \fBgenerate\fP (_RandomAccessIterator __begin, _RandomAccessIterator __end)"
.br
.ti -1c
.RI "template<typename OutputIterator > void \fBparam\fP (OutputIterator __dest) const "
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBseed_seq\fP class generates sequences of seeds for random number generators. 
.PP
Definition at line 5300 of file random.h.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef uint_least32_t \fBstd::seed_seq::result_type\fP"The type of the seed vales. 
.PP
Definition at line 5305 of file random.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "std::seed_seq::seed_seq ()\fC [inline]\fP"Default constructor. 
.PP
Definition at line 5308 of file random.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
