.TH "std::shared_future" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::shared_future \- 
.PP
Primary template for \fBshared_future\fP.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::__basic_future< _Res >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBshared_future\fP (const \fBshared_future\fP &__sf)"
.br
.ti -1c
.RI "\fBshared_future\fP (\fBshared_future\fP &&__sf)"
.br
.ti -1c
.RI "\fBshared_future\fP (\fBfuture\fP< _Res > &&__uf)"
.br
.ti -1c
.RI "const _Res & \fBget\fP ()"
.br
.ti -1c
.RI "\fBshared_future\fP & \fBoperator=\fP (const \fBshared_future\fP &__sf)"
.br
.ti -1c
.RI "\fBshared_future\fP & \fBoperator=\fP (\fBshared_future\fP &&__sf)"
.br
.ti -1c
.RI "bool \fBvalid\fP () const "
.br
.ti -1c
.RI "void \fBwait\fP () const "
.br
.ti -1c
.RI "template<typename _Rep , typename _Period > bool \fBwait_for\fP (const \fBchrono::duration\fP< _Rep, _Period > &__rel) const "
.br
.ti -1c
.RI "template<typename _Clock , typename _Duration > bool \fBwait_until\fP (const \fBchrono::time_point\fP< _Clock, _Duration > &__abs) const "
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef \fB__future_base::_Result\fP< _Res > & \fB__result_type\fP"
.br
.ti -1c
.RI "typedef \fBshared_ptr\fP< \fB_State\fP > \fB__state_type\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB__result_type\fP \fB_M_get_result\fP ()"
.br
.ti -1c
.RI "void \fB_M_swap\fP (\fB__basic_future\fP &__that)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Res> class std::shared_future< _Res >"
Primary template for \fBshared_future\fP. 
.PP
Definition at line 683 of file future.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename _Res > \fBstd::shared_future\fP< _Res >::\fBshared_future\fP (const \fBshared_future\fP< _Res > & __sf)\fC [inline]\fP"
.PP
Copy constructor. 
.PP
Definition at line 691 of file future.
.SS "template<typename _Res > \fBstd::shared_future\fP< _Res >::\fBshared_future\fP (\fBfuture\fP< _Res > && __uf)\fC [inline]\fP"
.PP
Construct from a future rvalue. 
.PP
Definition at line 694 of file future.
.SS "template<typename _Res > \fBstd::shared_future\fP< _Res >::\fBshared_future\fP (\fBshared_future\fP< _Res > && __sf)\fC [inline]\fP"
.PP
Construct from a \fBshared_future\fP rvalue. 
.PP
Definition at line 699 of file future.
.SH "Member Function Documentation"
.PP 
.SS "template<typename _Res> \fB__result_type\fP \fBstd::__basic_future\fP< _Res >::_M_get_result ()\fC [inline, protected, inherited]\fP"
.PP
Wait for the state to be ready and rethrow any stored exception. 
.PP
Definition at line 513 of file future.
.PP
Referenced by std::shared_future< _Res >::get(), std::future< void >::get(), and std::future< _Res >::get().
.SS "template<typename _Res > const _Res& \fBstd::shared_future\fP< _Res >::get ()\fC [inline]\fP"
.PP
Retrieving the value. 
.PP
Definition at line 717 of file future.
.PP
References std::__basic_future< _Res >::_M_get_result().

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
