std::time_put
NAME
std::time_put -
Primary class template time_put.
This facet encapsulates the code to format and output dates and times according to formats used by strftime().
SYNOPSIS
Inherits std::locale::facet.
Inherited by std::time_put_byname< _CharT, _OutIter >.
Public Types
typedef _CharT char_type
typedef _OutIter iter_type
Public Member Functions
time_put (size_t __refs=0)
iter_type put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, char __format, char __mod=0) const
iter_type put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, const _CharT *__beg, const _CharT *__end) const
Static Public Attributes
static locale::id id
Protected Member Functions
virtual ~time_put ()
virtual iter_type do_put (iter_type __s, ios_base &__io, char_type __fill, const tm *__tm, char __format, char __mod) const
Static Protected Member Functions
static __c_locale _S_clone_c_locale (__c_locale &__cloc) throw ()
static void _S_create_c_locale (__c_locale &__cloc, const char *__s, __c_locale __old=0)
static void _S_destroy_c_locale (__c_locale &__cloc)
static __c_locale _S_get_c_locale ()
static _GLIBCXX_CONST const char * _S_get_c_name () throw ()
static __c_locale _S_lc_ctype_c_locale (__c_locale __cloc, const char *__s)
Friends
class locale::_Impl
Detailed Description
template<typename _CharT, typename _OutIter> class std::time_put< _CharT, _OutIter >
Primary class template time_put.
This facet encapsulates the code to format and output dates and times according to formats used by strftime().
The time_put template uses protected virtual functions to provide the actual results. The public accessors forward the call to the virtual functions. These virtual functions are hooks for developers to implement the behavior they require from the time_put facet.
Definition at line 710 of file locale_facets_nonio.h.
Member Typedef Documentation
template<typename _CharT , typename _OutIter > typedef _CharT std::time_put< _CharT, _OutIter >::char_type
Public typedefs.
Reimplemented in std::time_put_byname< _CharT, _OutIter >.
Definition at line 716 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIter > typedef _OutIter std::time_put< _CharT, _OutIter >::iter_type
Public typedefs.
Reimplemented in std::time_put_byname< _CharT, _OutIter >.
Definition at line 717 of file locale_facets_nonio.h.
Constructor & Destructor Documentation
template<typename _CharT , typename _OutIter > std::time_put< _CharT, _OutIter >::time_put (size_t __refs = 0) [inline, explicit]
Constructor performs initialization. This is the constructor provided by the standard.
Parameters:
refs Passed to the base facet class.
Definition at line 731 of file locale_facets_nonio.h.
template<typename _CharT , typename _OutIter > virtual std::time_put< _CharT, _OutIter >::~time_put () [inline, protected, virtual]
Destructor.
Definition at line 777 of file locale_facets_nonio.h.
Member Function Documentation
template<typename _CharT , typename _OutIter > _OutIter std::time_put< _CharT, _OutIter >::do_put (iter_type __s, ios_base & __io, char_type __fill, const tm * __tm, char __format, char __mod) const [protected, virtual]
Format and output a time or date. This function formats the data in struct tm according to the provided format char and optional modifier. This function is a hook for derived classes to change the value returned.
See also:
put() for more details.
Parameters:
s The stream to write to.
io Source of locale.
fill char_type to use for padding.
tm Struct tm with date and time info to format.
format Format char.
mod Optional modifier char.
Returns:
Iterator after writing.
Definition at line 1175 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), and std::__ctype_abstract_base< _CharT >::widen().
Referenced by std::time_put< _CharT, _OutIter >::put().
template<typename _CharT , typename _OutIter > _OutIter std::time_put< _CharT, _OutIter >::put (iter_type __s, ios_base & __io, char_type __fill, const tm * __tm, const _CharT * __beg, const _CharT * __end) const
Format and output a time or date. This function formats the data in struct tm according to the provided format string. The format string is interpreted as by strftime().
Parameters:
s The stream to write to.
io Source of locale.
fill char_type to use for padding.
tm Struct tm with date and time info to format.
beg Start of format string.
end End of format string.
Returns:
Iterator after writing.
Definition at line 1140 of file locale_facets_nonio.tcc.
References std::ios_base::_M_getloc(), std::time_put< _CharT, _OutIter >::do_put(), and std::__ctype_abstract_base< _CharT >::narrow().
template<typename _CharT , typename _OutIter > iter_type std::time_put< _CharT, _OutIter >::put (iter_type __s, ios_base & __io, char_type __fill, const tm * __tm, char __format, char __mod = 0) const [inline]
Format and output a time or date. This function formats the data in struct tm according to the provided format char and optional modifier. The format and modifier are interpreted as by strftime(). It does so by returning time_put::do_put().
Parameters:
s The stream to write to.
io Source of locale.
fill char_type to use for padding.
tm Struct tm with date and time info to format.
format Format char.
mod Optional modifier char.
Returns:
Iterator after writing.
Definition at line 770 of file locale_facets_nonio.h.
References std::time_put< _CharT, _OutIter >::do_put().
Member Data Documentation
template<typename _CharT , typename _OutIter > locale::id std::time_put< _CharT, _OutIter >::id [static]
Numpunct facet id.
Definition at line 721 of file locale_facets_nonio.h.
Author
Generated automatically by Doxygen for libstdc++ from the source code.