.TH "std::tr1" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1 \- 
.PP
ISO C++ TR1 entities toplevel namespace is \fBstd::tr1\fP.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fB__detail\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__is_member_pointer_helper\fP"
.br
.RI "\fIis_member_pointer \fP"
.ti -1c
.RI "struct \fBadd_const\fP"
.br
.RI "\fI\fBadd_const\fP \fP"
.ti -1c
.RI "struct \fBadd_cv\fP"
.br
.RI "\fI\fBadd_cv\fP \fP"
.ti -1c
.RI "struct \fBadd_pointer\fP"
.br
.RI "\fI\fBadd_pointer\fP \fP"
.ti -1c
.RI "struct \fBadd_volatile\fP"
.br
.RI "\fI\fBadd_volatile\fP \fP"
.ti -1c
.RI "struct \fBalignment_of\fP"
.br
.RI "\fI\fBalignment_of\fP \fP"
.ti -1c
.RI "struct \fBarray\fP"
.br
.RI "\fIA standard container for storing a fixed size sequence of elements. \fP"
.ti -1c
.RI "class \fBbad_weak_ptr\fP"
.br
.RI "\fIException possibly thrown by \fC\fBshared_ptr\fP\fP. \fP"
.ti -1c
.RI "struct \fBextent\fP"
.br
.RI "\fIextent \fP"
.ti -1c
.RI "struct \fBhas_virtual_destructor\fP"
.br
.RI "\fI\fBhas_virtual_destructor\fP \fP"
.ti -1c
.RI "struct \fBintegral_constant\fP"
.br
.RI "\fI\fBintegral_constant\fP \fP"
.ti -1c
.RI "struct \fBis_abstract\fP"
.br
.RI "\fI\fBis_abstract\fP \fP"
.ti -1c
.RI "struct \fBis_arithmetic\fP"
.br
.RI "\fI\fBis_arithmetic\fP \fP"
.ti -1c
.RI "struct \fBis_array\fP"
.br
.RI "\fI\fBis_array\fP \fP"
.ti -1c
.RI "struct \fBis_class\fP"
.br
.RI "\fI\fBis_class\fP \fP"
.ti -1c
.RI "struct \fBis_compound\fP"
.br
.RI "\fI\fBis_compound\fP \fP"
.ti -1c
.RI "struct \fBis_const\fP"
.br
.RI "\fI\fBis_const\fP \fP"
.ti -1c
.RI "struct \fBis_empty\fP"
.br
.RI "\fI\fBis_empty\fP \fP"
.ti -1c
.RI "struct \fBis_enum\fP"
.br
.RI "\fI\fBis_enum\fP \fP"
.ti -1c
.RI "struct \fBis_floating_point\fP"
.br
.RI "\fI\fBis_floating_point\fP \fP"
.ti -1c
.RI "struct \fBis_function\fP"
.br
.RI "\fI\fBis_function\fP \fP"
.ti -1c
.RI "struct \fBis_fundamental\fP"
.br
.RI "\fI\fBis_fundamental\fP \fP"
.ti -1c
.RI "struct \fBis_integral\fP"
.br
.RI "\fI\fBis_integral\fP \fP"
.ti -1c
.RI "struct \fBis_member_function_pointer\fP"
.br
.RI "\fI\fBis_member_function_pointer\fP \fP"
.ti -1c
.RI "struct \fBis_member_object_pointer\fP"
.br
.RI "\fI\fBis_member_object_pointer\fP \fP"
.ti -1c
.RI "struct \fBis_object\fP"
.br
.RI "\fI\fBis_object\fP \fP"
.ti -1c
.RI "struct \fBis_pointer\fP"
.br
.RI "\fI\fBis_pointer\fP \fP"
.ti -1c
.RI "struct \fBis_polymorphic\fP"
.br
.RI "\fI\fBis_polymorphic\fP \fP"
.ti -1c
.RI "struct \fBis_same\fP"
.br
.RI "\fI\fBis_same\fP \fP"
.ti -1c
.RI "struct \fBis_scalar\fP"
.br
.RI "\fI\fBis_scalar\fP \fP"
.ti -1c
.RI "struct \fBis_union\fP"
.br
.RI "\fI\fBis_union\fP \fP"
.ti -1c
.RI "struct \fBis_void\fP"
.br
.RI "\fI\fBis_void\fP \fP"
.ti -1c
.RI "struct \fBis_volatile\fP"
.br
.RI "\fI\fBis_volatile\fP \fP"
.ti -1c
.RI "struct \fBrank\fP"
.br
.RI "\fIrank \fP"
.ti -1c
.RI "struct \fBremove_all_extents\fP"
.br
.RI "\fI\fBremove_all_extents\fP \fP"
.ti -1c
.RI "struct \fBremove_const\fP"
.br
.RI "\fI\fBremove_const\fP \fP"
.ti -1c
.RI "struct \fBremove_cv\fP"
.br
.RI "\fI\fBremove_cv\fP \fP"
.ti -1c
.RI "struct \fBremove_extent\fP"
.br
.RI "\fI\fBremove_extent\fP \fP"
.ti -1c
.RI "struct \fBremove_pointer\fP"
.br
.RI "\fI\fBremove_pointer\fP \fP"
.ti -1c
.RI "struct \fBremove_volatile\fP"
.br
.RI "\fI\fBremove_volatile\fP \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< bool, false > \fBfalse_type\fP"
.br
.ti -1c
.RI "typedef \fBintegral_constant\fP< bool, true > \fBtrue_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_acos\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_acosh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_asin\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_asinh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_atan\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fB__complex_atanh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "void \fB__throw_bad_weak_ptr\fP ()"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBacos\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBacosh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBarg\fP (_Tp __x)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBasin\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBasinh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBassoc_laguerre\fP (unsigned int __n, unsigned int __m, _Tp __x)"
.br
.ti -1c
.RI "float \fBassoc_laguerref\fP (unsigned int __n, unsigned int __m, float __x)"
.br
.ti -1c
.RI "long double \fBassoc_laguerrel\fP (unsigned int __n, unsigned int __m, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBassoc_legendre\fP (unsigned int __l, unsigned int __m, _Tp __x)"
.br
.ti -1c
.RI "float \fBassoc_legendref\fP (unsigned int __l, unsigned int __m, float __x)"
.br
.ti -1c
.RI "long double \fBassoc_legendrel\fP (unsigned int __l, unsigned int __m, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBatan\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBatanh\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tpx , typename _Tpy > __gnu_cxx::__promote_2< _Tpx, _Tpy >::__type \fBbeta\fP (_Tpx __x, _Tpy __y)"
.br
.ti -1c
.RI "float \fBbetaf\fP (float __x, float __y)"
.br
.ti -1c
.RI "long double \fBbetal\fP (long double __x, long double __y)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBcomp_ellint_1\fP (_Tp __k)"
.br
.ti -1c
.RI "float \fBcomp_ellint_1f\fP (float __k)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_1l\fP (long double __k)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBcomp_ellint_2\fP (_Tp __k)"
.br
.ti -1c
.RI "float \fBcomp_ellint_2f\fP (float __k)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_2l\fP (long double __k)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpn > __gnu_cxx::__promote_2< _Tp, _Tpn >::__type \fBcomp_ellint_3\fP (_Tp __k, _Tpn __nu)"
.br
.ti -1c
.RI "float \fBcomp_ellint_3f\fP (float __k, float __nu)"
.br
.ti -1c
.RI "long double \fBcomp_ellint_3l\fP (long double __k, long double __nu)"
.br
.ti -1c
.RI "template<typename _Tpa , typename _Tpc , typename _Tp > __gnu_cxx::__promote_3< _Tpa, _Tpc, _Tp >::__type \fBconf_hyperg\fP (_Tpa __a, _Tpc __c, _Tp __x)"
.br
.ti -1c
.RI "float \fBconf_hypergf\fP (float __a, float __c, float __x)"
.br
.ti -1c
.RI "long double \fBconf_hypergl\fP (long double __a, long double __c, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBconj\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< typename __gnu_cxx::__promote< _Tp >::__type > \fBconj\fP (_Tp __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_i\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_if\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_il\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_j\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_jf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_jl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_bessel_k\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_bessel_kf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_bessel_kl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpnu , typename _Tp > __gnu_cxx::__promote_2< _Tpnu, _Tp >::__type \fBcyl_neumann\fP (_Tpnu __nu, _Tp __x)"
.br
.ti -1c
.RI "float \fBcyl_neumannf\fP (float __nu, float __x)"
.br
.ti -1c
.RI "long double \fBcyl_neumannl\fP (long double __nu, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpp > __gnu_cxx::__promote_2< _Tp, _Tpp >::__type \fBellint_1\fP (_Tp __k, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_1f\fP (float __k, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_1l\fP (long double __k, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpp > __gnu_cxx::__promote_2< _Tp, _Tpp >::__type \fBellint_2\fP (_Tp __k, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_2f\fP (float __k, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_2l\fP (long double __k, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Tpn , typename _Tpp > __gnu_cxx::__promote_3< _Tp, _Tpn, _Tpp >::__type \fBellint_3\fP (_Tp __k, _Tpn __nu, _Tpp __phi)"
.br
.ti -1c
.RI "float \fBellint_3f\fP (float __k, float __nu, float __phi)"
.br
.ti -1c
.RI "long double \fBellint_3l\fP (long double __k, long double __nu, long double __phi)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBexpint\fP (_Tp __x)"
.br
.ti -1c
.RI "float \fBexpintf\fP (float __x)"
.br
.ti -1c
.RI "long double \fBexpintl\fP (long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > _Tp \fBfabs\fP (const \fBstd::complex\fP< _Tp > &__z)"
.br
.ti -1c
.RI "template<std::size_t _Int, typename _Tp , std::size_t _Nm> _Tp & \fBget\fP (\fBarray\fP< _Tp, _Nm > &__arr)"
.br
.ti -1c
.RI "template<std::size_t _Int, class _Tp1 , class _Tp2 > const tuple_element< _Int, \fBstd::pair\fP< _Tp1, _Tp2 > >::type & \fBget\fP (const \fBstd::pair\fP< _Tp1, _Tp2 > &__in)"
.br
.ti -1c
.RI "template<std::size_t _Int, class _Tp1 , class _Tp2 > tuple_element< _Int, \fBstd::pair\fP< _Tp1, _Tp2 > >::type & \fBget\fP (\fBstd::pair\fP< _Tp1, _Tp2 > &__in)"
.br
.ti -1c
.RI "template<std::size_t _Int, typename _Tp , std::size_t _Nm> const _Tp & \fBget\fP (const \fBarray\fP< _Tp, _Nm > &__arr)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBhermite\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBhermitef\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBhermitel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp > __gnu_cxx::__promote_4< _Tpa, _Tpb, _Tpc, _Tp >::__type \fBhyperg\fP (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x)"
.br
.ti -1c
.RI "float \fBhypergf\fP (float __a, float __b, float __c, float __x)"
.br
.ti -1c
.RI "long double \fBhypergl\fP (long double __a, long double __b, long double __c, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBimag\fP (_Tp)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBlaguerre\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBlaguerref\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBlaguerrel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBlegendre\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBlegendref\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBlegendrel\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBnorm\fP (_Tp __x)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator!=\fP (const \fBarray\fP< _Tp, _Nm > &__one, const \fBarray\fP< _Tp, _Nm > &__two)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator<\fP (const \fBarray\fP< _Tp, _Nm > &__a, const \fBarray\fP< _Tp, _Nm > &__b)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator<=\fP (const \fBarray\fP< _Tp, _Nm > &__one, const \fBarray\fP< _Tp, _Nm > &__two)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator==\fP (const \fBarray\fP< _Tp, _Nm > &__one, const \fBarray\fP< _Tp, _Nm > &__two)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator>\fP (const \fBarray\fP< _Tp, _Nm > &__one, const \fBarray\fP< _Tp, _Nm > &__two)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> bool \fBoperator>=\fP (const \fBarray\fP< _Tp, _Nm > &__one, const \fBarray\fP< _Tp, _Nm > &__two)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > \fBstd::complex\fP< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > \fBpolar\fP (const _Tp &__rho, const _Up &__theta)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > \fBstd::complex\fP< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > \fBpow\fP (const _Tp &__x, const \fBstd::complex\fP< _Up > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > __gnu_cxx::__promote_2< _Tp, _Up >::__type \fBpow\fP (_Tp __x, _Up __y)"
.br
.ti -1c
.RI "long double \fBpow\fP (long double __x, long double __y)"
.br
.ti -1c
.RI "double \fBpow\fP (double __x, double __y)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const _Tp &__y)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const _Tp &__x, const \fBstd::complex\fP< _Tp > &__y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > \fBstd::complex\fP< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const _Up &__y)"
.br
.ti -1c
.RI "template<typename _Tp > \fBstd::complex\fP< _Tp > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const \fBstd::complex\fP< _Tp > &__y)"
.br
.ti -1c
.RI "float \fBpow\fP (float __x, float __y)"
.br
.ti -1c
.RI "template<typename _Tp , typename _Up > \fBstd::complex\fP< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > \fBpow\fP (const \fBstd::complex\fP< _Tp > &__x, const \fBstd::complex\fP< _Up > &__y)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBreal\fP (_Tp __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBriemann_zeta\fP (_Tp __x)"
.br
.ti -1c
.RI "float \fBriemann_zetaf\fP (float __x)"
.br
.ti -1c
.RI "long double \fBriemann_zetal\fP (long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_bessel\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBsph_besself\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBsph_bessell\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_legendre\fP (unsigned int __l, unsigned int __m, _Tp __theta)"
.br
.ti -1c
.RI "float \fBsph_legendref\fP (unsigned int __l, unsigned int __m, float __theta)"
.br
.ti -1c
.RI "long double \fBsph_legendrel\fP (unsigned int __l, unsigned int __m, long double __theta)"
.br
.ti -1c
.RI "template<typename _Tp > __gnu_cxx::__promote< _Tp >::__type \fBsph_neumann\fP (unsigned int __n, _Tp __x)"
.br
.ti -1c
.RI "float \fBsph_neumannf\fP (unsigned int __n, float __x)"
.br
.ti -1c
.RI "long double \fBsph_neumannl\fP (unsigned int __n, long double __x)"
.br
.ti -1c
.RI "template<typename _Tp , std::size_t _Nm> void \fBswap\fP (\fBarray\fP< _Tp, _Nm > &__one, \fBarray\fP< _Tp, _Nm > &__two)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ISO C++ TR1 entities toplevel namespace is \fBstd::tr1\fP. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
