.TH "std::tr1::__detail" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::__detail \- 
.PP
Implementation details not part of the namespace \fBstd::tr1\fP interface.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Implementation details not part of the namespace \fBstd::tr1\fP interface. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
