.TH "std::tr1::is_void" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::is_void \- 
.PP
\fBis_void\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBintegral_constant< bool,(__is_void_helper< remove_cv< _Tp >::type >::value)>\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< bool, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef bool \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::tr1::is_void< _Tp >"
\fBis_void\fP 
.PP
Definition at line 96 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
