.TH "std::tr1::alignment_of" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::alignment_of \- 
.PP
\fBalignment_of\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBintegral_constant< std::size_t, __alignof__(_Tp)>\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< std::size_t, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef std::size_t \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const std::size_t \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::tr1::alignment_of< _Tp >"
\fBalignment_of\fP 
.PP
Definition at line 350 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
