.TH "std::tr1::bad_weak_ptr" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::bad_weak_ptr \- 
.PP
Exception possibly thrown by \fC\fBshared_ptr\fP\fP.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBstd::exception\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual char const * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exception possibly thrown by \fC\fBshared_ptr\fP\fP. 
.PP
Definition at line 58 of file boost_sp_counted_base.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual char const* std::tr1::bad_weak_ptr::what () const  throw ()\fC [inline, virtual]\fP"Returns a C-style character string describing the general cause of the current error. 
.PP
Reimplemented from \fBstd::exception\fP.
.PP
Definition at line 62 of file boost_sp_counted_base.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
