.TH "std::tr1::integral_constant" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::integral_constant \- 
.PP
\fBintegral_constant\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by std::tr1::__is_floating_point_helper< typename >, std::tr1::__is_integral_helper< typename >, std::tr1::__is_member_function_pointer_helper< typename >, std::tr1::__is_member_object_pointer_helper< typename >, \fBstd::tr1::__is_member_pointer_helper< _Tp >\fP, std::tr1::__is_pointer_helper< typename >, std::tr1::__is_void_helper< typename >, \fBstd::tr1::is_array< typename >\fP, \fBstd::tr1::is_const< typename >\fP, \fBstd::tr1::is_function< typename >\fP, \fBstd::tr1::is_same< typename, typename >\fP, and \fBstd::tr1::is_volatile< typename >\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBintegral_constant\fP< _Tp, __v > \fBtype\fP"
.br
.ti -1c
.RI "typedef _Tp \fBvalue_type\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const _Tp \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp, _Tp __v> struct std::tr1::integral_constant< _Tp, __v >"
\fBintegral_constant\fP 
.PP
Definition at line 67 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
