.TH "std::tr1::remove_cv" 3 "Sun Oct 10 2010" "libstdc++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
std::tr1::remove_cv \- 
.PP
\fBremove_cv\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBremove_const\fP< typename \fBremove_volatile\fP< _Tp >::type >::type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename _Tp> struct std::tr1::remove_cv< _Tp >"
\fBremove_cv\fP 
.PP
Definition at line 418 of file tr1_impl/type_traits.

.SH "Author"
.PP 
Generated automatically by Doxygen for libstdc++ from the source code.
