std::weibull_distribution
NAME
std::weibull_distribution -
A weibull_distribution random number distribution.
SYNOPSIS
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
weibull_distribution (_RealType __a=_RealType(1), _RealType __b=_RealType(1))
weibull_distribution (const param_type &__p)
_RealType a () const
_RealType b () const
result_type max () const
result_type min () const
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator > result_type operator() (_UniformRandomNumberGenerator &__urng)
void param (const param_type &__param)
param_type param () const
void reset ()
Detailed Description
template<typename _RealType = double> class std::weibull_distribution< _RealType >
A weibull_distribution random number distribution.
The formula for the normal probability density function is: \[ p(x|\alpha,\beta) = \frac{\alpha}{\beta} (\frac{x}{\beta})^{\alpha-1} \xp{(-(\frac{x}{\beta})^\alpha)} \]
Definition at line 4335 of file random.h.
Member Typedef Documentation
template<typename _RealType = double> typedef _RealType std::weibull_distribution< _RealType >::result_type"The type of the range of the distribution.
Definition at line 4342 of file random.h.
Member Function Documentation
template<typename _RealType = double> _RealType std::weibull_distribution< _RealType >::a () const [inline]
Return the $a$ parameter of the distribution.
Definition at line 4393 of file random.h.
template<typename _RealType = double> _RealType std::weibull_distribution< _RealType >::b () const [inline]
Return the $b$ parameter of the distribution.
Definition at line 4400 of file random.h.
template<typename _RealType = double> result_type std::weibull_distribution< _RealType >::max () const [inline]
Returns the least upper bound value of the distribution.
Definition at line 4429 of file random.h.
template<typename _RealType = double> result_type std::weibull_distribution< _RealType >::min () const [inline]
Returns the greatest lower bound value of the distribution.
Definition at line 4422 of file random.h.
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::weibull_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng) [inline]
Generating functions.
Definition at line 4437 of file random.h.
References std::weibull_distribution< _RealType >::operator()(), and std::weibull_distribution< _RealType >::param().
Referenced by std::weibull_distribution< _RealType >::operator()().
template<typename _RealType = double> void std::weibull_distribution< _RealType >::param (const param_type & __param) [inline]
Sets the parameter set of the distribution. Parameters:
__param The new parameter set of the distribution.
Definition at line 4415 of file random.h.
template<typename _RealType = double> param_type std::weibull_distribution< _RealType >::param () const [inline]
Returns the parameter set of the distribution.
Definition at line 4407 of file random.h.
Referenced by std::weibull_distribution< _RealType >::operator()(), std::operator==(), and std::operator>>().
template<typename _RealType = double> void std::weibull_distribution< _RealType >::reset () [inline]
Resets the distribution state.
Definition at line 4386 of file random.h.
Author
Generated automatically by Doxygen for libstdc++ from the source code.